### ISSUE TITLE
Add register addresses to hover data

### ISSUE THREAD

**Issue by spec-chum** [prb28/vscode-amiga-assembly#100]
When displaying the hover info for hardware registers, would it be possible to add the address?

![image](https://user-images.githubusercontent.com/4376135/68803605-faed5280-0657-11ea-8d71-9a338246e254.png)
To show

`$100 - Bit Plane Control Register 0`
or
`$dff100 - Bit Plane Control Register 0`

**Comment by prb28** [comment]
Here is a preview of the feature: 
[amiga-assembly-0.19.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3854360/amiga-assembly-0.19.0.vsix.zip)

**Comment by spec-chum** [comment]
Only had time for a quick test, but seems to work as intended.

Thanks :+1:

**Comment by prb28** [comment]
Thanks, I'll add the short name of the register, that can be useful too.

**Comment by prb28** [comment]
Example:
DMACONR($dff002) - DMA Control (and blitter status) read

**Comment by spec-chum** [comment]
Even better :)
