### ISSUE TITLE
Multiple code SECTIONs cause debug output to be off

### ISSUE THREAD

**Issue by jonathanbennett73** [prb28/vscode-amiga-assembly#102]
Strange one here.  I originally had multiple files with code all with the same section name so that all the sections got merged at link-time. The debugging was working fine.  

Recently I've got the different files in different section names (to optimise loading/memory allocation) and I noticed that now if you debug that the CPU call stack/highlighted line is a few lines off compared to the disassembled memory pointer. The number of lines off seems to be related to the number of different code sections.

If it's not immediately obvious what is going on I can generate a test set of files for you.

**Comment by prb28** [comment]
Yes, please, if you have some example code, it will help me to reproduce and test.

**Comment by jonathanbennett73** [comment]
[example.zip](https://github.com/prb28/vscode-amiga-assembly/files/3883617/example.zip)

Spent all morning trying to get something small to show this. This is on Windows 10 x64.  It was so random it seems be only happen with code in different sections and is also influenced by the file size. You can add some size with dcb.w x,x and it changes the bug. Very weird. I'm assuming it's something to do with linedebug information getting messed up.

In the zip file there is gencop.s, test1.s, test2.s. Copy these into the example workspace.

Set a breakpoint in gencop.s on the line:
jsr        SubPartPreCalc_IntroStart

Run debug. It will stop on the jsr line. Then use f11 to step into the function. The bug will either cause a memory dissassembly to be shown (but on the correct instruction) or will open up the correct file but the highlighted debug line is wrong.

Then go into test.2 and change the code section from "randomsection" to "gencop" and rerun the debug (so gencop.s and test2.s are in the same code section). It should debug properly now.

**Comment by prb28** [comment]
Thanks for the example, and the time spent.
It really messes up the debugger. I'm debugging the debugger ;-).

**Comment by prb28** [comment]
Found the bug, I will have to patch FS-UAE and the extension.
Trying to have a more standard way to communicate with the gdb remote protocol, I've missed the fact that the debugger cannot estimate correctly the segment relocation by the emulator. So it must be sent by the remote server.

**Comment by jonathanbennett73** [comment]
Thanks for investigating. If you want me to test anything against my big-ish project then just let me know.

**Comment by prb28** [comment]
Thanks, and yes, when I'll have a windows binary of fs-uae for test I'll let you know.

**Comment by prb28** [comment]
Could you please try these binaries ?
https://github.com/prb28/vscode-amiga-assembly/releases/download/0.19-bin-test/bin-windows_x64.zip
I've found a new issue #105

**Comment by jonathanbennett73** [comment]
Quick initial test seemed to work ok. I set a breakpoint deep down in a 13 section exe and it stopped in the correct place. I'll do some more checks later :)

**Comment by prb28** [comment]
13 sections look like a crash test !
Thanks for the test.
