### ISSUE TITLE
Copper disassembly not working

### ISSUE THREAD

**Issue by spec-chum** [prb28/vscode-amiga-assembly#103]
Possibly me missing something obvious, but when I try to do a copper disassembly I always get this error:
![image](https://user-images.githubusercontent.com/4376135/69497726-1e29c480-0ed8-11ea-83ca-0b8a612bce13.png)

It's the same error (with different parameter, obviously) whether I choose 1, 2, symbol or memory address.

Tested with own code and original gencop.s from example workspace, same error.

**Comment by prb28** [comment]
Does it work in the call stack view (copper thread) ?

**Comment by spec-chum** [comment]
No, same error actually.  Didn't try that before.

**Comment by prb28** [comment]
Could you please activate "Toggle developer tools" in the Help menu and retrieve the console ?

**Comment by spec-chum** [comment]
`log.ts:196   ERR The Gdb connection is not opened: Error: The Gdb connection is not opened
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async R.sendExceptionBreakpoints (file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5175:114)
    at async q.sendToOneOrAllSessions (file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5206:174)
    at async q.sendAllBreakpoints (file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5205:245)
    at async file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:850
log.ts:196   ERR File not found (c:\Users\specc\Desktop\vscode-amiga-wks-example\bin\fs-uae.exeStarting): Error: File not found (c:\Users\specc\Desktop\vscode-amiga-wks-example\bin\fs-uae.exeStarting)
    at S.resolve (file:///C:/Users/specc/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1555:706)
2console.ts:137 [Extension Host] (node:11512) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
notificationsAlerts.ts:40 Unable to disassemble; invalid parameters [object Object]
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
2notificationsAlerts.ts:40 cannot open disassembly:copper_1__3000.dbgasm. Detail: Unable to disassemble; invalid parameters [object Object]
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Unable to disassemble; invalid parameters [object Object]
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] stack trace: Error: Unable to disassemble; invalid parameters [object Object]	at DebugDisassembledMananger.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:391:28)	at Generator.next (<anonymous>)	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:7:71	at new Promise (<anonymous>)	at __awaiter (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:3:12)	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:362:49	at new Promise (<anonymous>)	at DebugDisassembledMananger.disassembleRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:362:16)	at FsUAEDebugSession.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:287:50)	at Generator.next (<anonymous>)	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:7:71	at new Promise (<anonymous>)	at __awaiter (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:3:12)	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:286:49	at new Promise (<anonymous>)	at FsUAEDebugSession.disassembleRequestInner (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:286:16)	at FsUAEDebugSession.disassembleRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:301:21)	at FsUAEDebugSession.dispatchRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\debugSession.js:447:22)	at FsUAEDebugSession._handleData (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\protocol.js:97:38)	at Socket.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\protocol.js:18:44)	at Socket.emit (events.js:200:13)	at addChunk (_stream_readable.js:294:12)	at readableAddChunk (_stream_readable.js:275:11)	at Socket.Readable.push (_stream_readable.js:210:10)	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:65 [[object Object]]Unable to disassemble; invalid parameters [object Object]
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 Error: Unable to disassemble; invalid parameters [object Object]
	at DebugDisassembledMananger.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:391:28)
	at Generator.next (<anonymous>)
	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:3:12)
	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:362:49
	at new Promise (<anonymous>)
	at DebugDisassembledMananger.disassembleRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\debugDisassembled.js:362:16)
	at FsUAEDebugSession.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:287:50)
	at Generator.next (<anonymous>)
	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:3:12)
	at c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:286:49
	at new Promise (<anonymous>)
	at FsUAEDebugSession.disassembleRequestInner (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:286:16)
	at FsUAEDebugSession.disassembleRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\out\fsUAEDebug.js:301:21)
	at FsUAEDebugSession.dispatchRequest (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\debugSession.js:447:22)
	at FsUAEDebugSession._handleData (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\protocol.js:97:38)
	at Socket.<anonymous> (c:\Users\specc\.vscode\extensions\prb28.amiga-assembly-0.19.0\node_modules\vscode-debugadapter\lib\protocol.js:18:44)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166`

**Comment by prb28** [comment]
Well, that's interesting, thanks.
It seems that vscode is calling a standard disassembleRequest on the extension debugger. And it's the first time this code is called (it was a beta feature in the past version of vscode and I did it in case of a new view in vscode).
Could you please try to disable all other extension in the workspace ?
I think maybe one of them is making some trouble.
Otherwise, can I give you a debug extension code to test ?

**Comment by spec-chum** [comment]
Aha, bingo.

As soon as you put that I knew what extension it was.

I've disabled barman's GCC extension and it works now.

**Comment by prb28** [comment]
Great !
I'll keep it in mind for the next time I've an issue with a strange behavior.
The two extensions may have some identical declarations, and vscode may not know how to route some events.
