### ISSUE TITLE
-linedebug not working with new vasm

### ISSUE THREAD

**Issue by spec-chum** [prb28/vscode-amiga-assembly#104]
There was a "fix" for vasm in 1.8g:
`output-hunk: Fixed LINE debug hunk output (-linedebug). Now it can deal with code from multiple sources and the line numbers for executing macros and repetitions are correct.`

Which makes it so no breakpoints hit when used on the extension.

Not sure what details you need?

**Comment by prb28** [comment]
Did you build it yourself with the latest sources ?
The vasm I've bundled is a 1.8g snapshot just before the release (some days before), I've to try with the latest sources to check it.

**Comment by spec-chum** [comment]
Yeah, built it couple weeks ago from source with GCC 9.2

**Comment by prb28** [comment]
Got it working with my build project: https://github.com/prb28/vasm on osx.
If you want to try it, clone the repository and type:
`./gradlew vasmm68k_motX86_64Executable`
You will find the binary in the path: *build/exe/vasmm68k_mot/x86_64/vasmm68k_mot*
It should build on osx, linux and windows.
