### ISSUE TITLE
Bug in Add Bitwise operators to calculations

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#110]
In the new cool feature "Add Bitwise operators to calculations" is unfortunately a bug in the AND operator.

befor:
  dc.b $10,$21,$10,$41,$10,$61

operator:
 x&16

after:
  dc.b $10,$21,$10,$41,$10,$61

expected:
  dc.b $10,$00,$10,$00,$10,$00

**Comment by prb28** [comment]
"new cool feature" ... don't know who filled a feature request ;-).

You are right, it works with "x+3" but not with bitwise operator.
I didn't expect that in my tests!

Thanks for the issue.

**Comment by prb28** [comment]
It's a bug with the 0 value after calculation.

**Comment by prb28** [comment]
fix in https://github.com/prb28/vscode-amiga-assembly/releases/download/0.19.1-test/amiga-assembly-0.19.1.vsix
