### ISSUE TITLE
Current directory wrong when debugging

### ISSUE THREAD

**Issue by Muzza** [prb28/vscode-amiga-assembly#112]
If I put 'file.raw' next to 'gencop' in the hd0 folder, and run the project, I can load it through dos.library Open/Read using a relative filename. e.g.:
filename:	dc.b 'file.raw',0

When running using the debug mode however, it would seem that the current directory is not the same, and loading the file fails. It does work though if I give a full path to the filename e.g.:
filename:	dc.b 'dh0:file.raw',0

Is this a bug? Or an issue with how the debug mode works?

(Thank you for this great project BTW - it has got me back into AMIGA programming in a big way!)

**Comment by prb28** [comment]
First... thanks ! I’m always happy to see it’s useful.

This issue might be related to this one: https://github.com/prb28/vscode-amiga-assembly/issues/81#issuecomment-524666451.

It might be a missing call before the debug command to set the current directory.
I’ll look in the docs to see how to set it.
(It may only work with a Kickstart >2.)

**Comment by prb28** [comment]
Partial fix: https://github.com/prb28/fs-uae/commit/7b878537f9ba4d8135355a7c9192a4964f350789

**Comment by prb28** [comment]
Partial fix build in the binaries : https://github.com/prb28/vscode-amiga-wks-example/releases/tag/0.19-1

**Comment by prb28** [comment]
new integration  of fs-uae should fix this issue.
