### ISSUE TITLE
Memory Viewer

### ISSUE THREAD

**Issue by mfroeschl** [prb28/vscode-amiga-assembly#113]
Hello,

first of all thank you very much for making this great extension. So far I enjoy it very much.

There is however a feature I am missing (or I can't seem to find it), and that it a memory viewer which allows for monitoring the memory while debugging, scrolling through memory and jumping to addresses or symbols, etc. Basically what MonAm has in the lower right corner.

In the Wiki, there's a section that explains how to do a memory dump via command line,
but that is very tedious and only seems to yield one line at a time.

Having a dedicated window in Visual Studio to do this would be so much more efficient. Is any such feature available or planned?

**Comment by prb28** [comment]
Hi,
(I'm happy to hear you like it !)
I know it's a tricky part of the extension but you can do many thing with the debug console and watch and the command: `m ${register|symbol}, #{symbol}, size[, wordSizeInBytes, rowSizeInWords]`
To get the memory pointed by the value **in** the `copper` symbol address you can try:
`m #{copperlist},300, 2, 5`
This will show you memory grouped by 2 bytes with 5 groups by line.
```
>01fc 0000 0100 0200 0180 | .ü........
     00005850:01fc 0000 0100 0200 0180 | .ü........
     0000585a:0349 2b07 fffe 0180 056c | .I+.ÿþ...l
     00005864:2c07 fffe 0180 0113 8007 | ,.ÿþ......
...
```
Don't forget to click on the arrow in the left part of the expression to view the lines.
And you can add it to the watch view to have a real-time modification view:
![ScreenCaptureDebug2](https://user-images.githubusercontent.com/10462286/77246846-614c3800-6c2b-11ea-9d35-cba3dbba642e.png)

Does this answer your request ?

**Comment by mfroeschl** [comment]
Hello prb28,

thank you so much for your quick reply. Adding it to the watch did the trick for me, this way it really comes in very handy.

It would still be neat if it was possible to have a watch for basically all the memory (like MonAm), or if there was a quicker way to add the symbols to the watch (e.g. via right click), to speed up the debugging.

I am still pretty new to both Amiga programming and VS Code and was struggling with the following items:

- The memory dump command will give me `Expression not recognized` for my symbols if they contain an underscore, e.g. `#{MEM_POINTER}` will not work but `#{MEMPOINTER}` (w/o underscore) will work. I don't know if this is an issue with the extension or FSUAE or just spec.
- At first I did not realize that the results of the memory dump in the console were folded, that's why I thought there was only 1 line of result... my bad!

I don't know if those are common issues to be worth mentioning in the Wiki, but I thought I'd bring it to your attention anyway.

Cheers!

**Comment by prb28** [comment]
if copperlist is a symbol indicating address $1fc (after program load) and containing value $5f0.
```
copperlist:   DC.L        $5f0
```
There is different ways to set the starting address of a memory dump:
- using the memory address: `m 01fc,300, 2, 5` will dump starting at $01fc
- starting with ${copperlist}: will dump using starting at copperlist address (position of the symbol in memory) -> $1fc
- starting with #{copperlist}: will dump using starting at copperlist value (value of the coppelist symbol in memory -> $5f0

To have all memory, you can dump from $0 but all the memory maybe not readable.

I'll keep the right-click idea, that should be a easier way to do it.

**Comment by Real-MJoe** [comment]
**Off Topic:**
Damn this feature i have missing too. But its still present. Yes bady :) 
This should be included in the Wiki with an example.

pepe

**Comment by prb28** [comment]
Memory breakpoint is a good idea, but I don’t think FS-UAE is ready for that. I have to check it.

And yes, I need to add it to the wiki.

**Comment by Real-MJoe** [comment]
Are there any new advances in terms of memory breakpoint?

**Comment by Real-MJoe** [comment]
Is a memory breakpoint possible with WinUAE?

**Comment by prb28** [comment]
I think there is some code for that in winuae. I watched it some moths ago... I'll be back on this project soon. I'll add a feature request.

**Comment by phaze101** [comment]
@Real-MJoe thank you for pointing me to this. Exactly what I was looking for.

Is this in the documentation on the Wiki? If not can it be included so that beginners will know how to do it.

**Comment by prb28** [comment]
Here : https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#memory-dump
