### ISSUE TITLE
WinUAE GDB Support

### ISSUE THREAD

**Issue by jonathanbennett73** [prb28/vscode-amiga-assembly#114]
Hi,
I don't know how the internals work of your GDB additions, but is there any possibility that they are close to the GDB additions Bartman made to WinUAE?
[https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/bin/](url)

I use WinUAE for all my dev and only have to use fs-uae when I'm debugging. I'd much prefer to use WinUAE for everything. I don't know if it's as simple as adding a new debug launch snippet or if the GDB implementation is totally incompatible and this isn't possible.

**Comment by prb28** [comment]
Hi,
I agree a lot of amiga devs are on windows with WinUAE (not me, but I'm not really an amiga dev).

First, yes they are close to the additions of Bartman, with some (many) tweaks.
There is "some" work to be done to achieve it and I prefer to wait for a merge to the main project of Toni Wilem, before starting adding my code (I have talked about that with him).
I think that will be a great benefit it is not in a lonely fork as my actual modifications in FsUAE, it is the only way to stay "up to date".

**Comment by jonathanbennett73** [comment]
Ok cool. Let me know if you need any testing or help.

**Comment by prb28** [comment]
Well, thanks, but, unfortunately, don't expect a rapid issue.
I've talked to Tony about this in september 2019, he was ready to start the merge, and I've no news about it since...

**Comment by prb28** [comment]
If someone has time to test the beta version, I'll appreciate to have some feedback.
https://github.com/prb28/vscode-amiga-assembly/releases/tag/0.21

**Comment by prb28** [comment]
New "pre" version at the same place :
- StopOnEntry fixed.
- Use of UAEexit at the end of the example program startup-sequence.
- New launch parameters :
    *"exceptionMask": 8188,
    *"emulatorStartDelay": 1500

**Comment by prb28** [comment]
New pre-release bug of stacktrace fixed.

**Comment by jonathanbennett73** [comment]
What does the exception mask do?
Antiriad

**Comment by prb28** [comment]
Hi !
It corresponds to the tasks exceptions : https://wiki.amigaos.net/wiki/Exec_Tasks#Task_Exceptions
You can filter by setting the corresponding bit to 1.
(It's not really clear in my mind ... maybe some guru of winuae exception's traps would have a better insight, it's used in the command debugger of winuae)
