### ISSUE TITLE
In-editor debugger does not stop at breakpoints

### ISSUE THREAD

**Issue by johngirvin** [prb28/vscode-amiga-assembly#115]
I can assemble and run (in run and debug mode) a (sizable) program, but the in-editor debugger does not stop at breakpoints, no matter where I put them in the source.

The program is ~50k lines (a game) and consists of a main.s file that INCLUDEs the other sources and binary files. main.s is in the workspace root directory and the other source files are in a subdirectories. A little unusal, but it's a legacy source base originally developed in Devpac.

The console debugger seems to work, and the in-editor debugger works if I replace main.s with the gencop.s demo source.

**Comment by prb28** [comment]
The breakpoints are resolved with the linedebug information in the .o files.
You can see it with a hex dump of the .o files and the exe file.

Some questions:
- Do you use a makefile ?
- Is the breakpoint red ?
- Did you you try the stop at the program entry ?

I've had some issues with that in the past, but I need to debug it to tell you what's happening.
If you can make a small program that I can debug, that would be great.

**Comment by johngirvin** [comment]
I did a hex dump of the binary and see 700+ "LINE" strings. I don't know how to interpret the data around them though.

No makefile, for now I'm building in terminal with:
```
bin/vasmm68k_mot -m68000 -no-fpu -Fhunk -linedebug main.s -o build/main.o
bin/vlink -bamigahunk -Bstatic build/main.o -o fs-uae/hd0/main
```

The breakpoints are all red.

Stop at entry works OK.

**Comment by prb28** [comment]
Maybe there is a problem to resolve the sources path. 
In the hexdump you will find the sources files with their path, and they should be absolute.

Can you try to build the main.s file with it's absolute path ?
That should be done by the build command of the extension
or in the shell with the following command:
```
bin/vasmm68k_mot -m68000 -no-fpu -Fhunk -linedebug /my/path/to/workspace/main.s -o build/main.o
```

**Comment by johngirvin** [comment]
Tried building with main.s absolute path - no difference.

The paths in the LINE data are absolute and correct.

FWIW, I get this when the Amiga is booting. I don't know what it is, but it only happens in debug mode. There's nothing in the s/startup-sequence other than SetPatch and my binary, and SetPatch runs sucessfully after this requester appears.

![image](https://user-images.githubusercontent.com/672750/83693178-75c68c80-a5ed-11ea-9de6-03400b810040.png)

**Comment by prb28** [comment]
Googling it, I found this thread: http://eab.abime.net/showthread.php?t=36158

> when a program tries to execute a FPU instruction on a processor without a FPU, or there is a problem with the 68040/060 library.
> 8000000B Line F emulation error 
I don't know if it helps, do you use a FPU library ?

If the entry breakpoint works can you step in the the program source ?

**Comment by johngirvin** [comment]
When you launch with the debugger, does it use startup-sequence or is it another method?

Pausing on start then stepping through the code, the game is actually failing opening lowlevel.library (I have it in fs-uae/hd0/libs/) and quitting, but then launches anyway.

I'm guessing the debugger launches the game in an early or unusual environment where lowlevel can't be found, it fails and quits, then startup-sequence launches it again but this time lowlevel _can_ be opened and it starts up. The second launch would explain why the debugger appears to be not working I guess.

**Comment by prb28** [comment]
There is two different problems:

1. The double run is explained here: https://github.com/prb28/vscode-amiga-assembly/wiki/FAQ#when-starting-the-emulator-runs-twice-before-returning-to-the-ide
2. I thinks it's the library file resolution that doesn't work in FsUAE, it is related to the issue https://github.com/prb28/vscode-amiga-assembly/issues/112, please try to load it with an absolute amiga path "dh0:libs/lowlevel.library"

**Comment by johngirvin** [comment]
I've been unable to load lowlevel.library by path. Libraries on disk can't be loaded until AmigaDOS is started (according to the exec autodocs), which may be related.

However, now you've explained what's going on with the debug startup environment, I was able to get the extension's in-editor debugger to stop at breakpoints in the game code, single-step and so on. So, apologies, there's not actually an issue with the debugger here after all.

**Comment by prb28** [comment]
Great !
