### ISSUE TITLE
_ in variable

### ISSUE THREAD

**Issue by hypp** [prb28/vscode-amiga-assembly#117]
Hi!

It seems to me that 
[this regex](https://github.com/prb28/vscode-amiga-assembly/blob/1dcca262a954da42dbfbfae90ff94c8f61ed88fe/src/fsUAEDebug.ts#L911)
forbids labels with containing an _ (underscore).

Is there a reason for that or can it be changed?

**Comment by prb28** [comment]
Hi,
It looks like it’s missing, you’re right.
Thanks for reporting.

**Comment by prb28** [comment]
Here is the fix if you want to test it.
[amiga-assembly-0.20.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/4874710/amiga-assembly-0.20.0.vsix.zip)

**Comment by hypp** [comment]
Works for me. Thanks for fixing!
