### ISSUE TITLE
Better instruction's documentation not work

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#120]
The new feature in 0.20 "Better instruction's documentation" not work for me.  Only the following tooltip is displayed. :( 

![grafik](https://user-images.githubusercontent.com/40276633/88708609-365f7c80-d114-11ea-97a2-6a7ce6054642.png)

**Comment by Real-MJoe** [comment]
After extension disabled...close/open VS Code...uninstall extention.....close/open VS Code.....install extention.....close/open VS Code the better documentation ist showed now!  Very nice :) 

But...one small bug i noticed though.If you scroll down in the tooltip and then go over another command, the scroll position is not set ontop. The scroll position is still the same as the last command.

**Comment by prb28** [comment]
Thanks for testing uninstall/ install to resolve this issue.

Yes I've seen the scrolling problem, but I'm not sure to be able to fix it. I'll try.
