### ISSUE TITLE
Feature: Show CCR (Conditional Code Register)  at debugging

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#122]
It would be helpful if in debug mode the CCR (Conditional Code Register) is displayed. If this is possible or if FS-UAE has to be drilled out again.

**Comment by prb28** [comment]
@Real-MJoe Please, try this and tell if it works for you.
[amiga-assembly-0.21.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/5105540/amiga-assembly-0.21.0.vsix.zip)

**Comment by Real-MJoe** [comment]
This version have many bugs. So i can not create and run a new file. Follow error is showing:
![grafik](https://user-images.githubusercontent.com/40276633/90862318-8e914380-e38d-11ea-9475-07a665db6e9a.png)

This is the content of the new file:
![grafik](https://user-images.githubusercontent.com/40276633/90862363-9e108c80-e38d-11ea-9903-d44db8f9f299.png)

In exist files the regitster (N,Z) wihle not work, sorry.

**Comment by prb28** [comment]
Fixed in fs-uae and winuae
