### ISSUE TITLE
Feature - Breakpoint with condition

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#125]
It is possible to add the feature breakpoints with condition. This would make debugging even better than it already is. In VS Code the condition can be entered as follows.
![image](https://user-images.githubusercontent.com/40276633/96083597-c3b5a000-0ebd-11eb-89cb-23a0b1ee553b.png)

Thank you and greetings
pepe

**Comment by prb28** [comment]
I agree it would be a good feature.
I don't know how gdb does it...
I'll take a look during my winuae integration.

**Comment by grahambates** [comment]
@prb28 just seen this could be closed as this feature was introduced in the last release.

**Comment by prb28** [comment]
Yes you're right.
