### ISSUE TITLE
vlink.exe: VCRUNTIME140.dll is missing from 'vscode-amiga-wks-example-windows_x64.zip'

### ISSUE THREAD

**Issue by DLehenbauer** [prb28/vscode-amiga-assembly#129]
Without this .dll, vlink.exe will silently exit when building the workspace from within VSCode (i.e., 'fs-uae/hd0/gencop' is not produced.)

You can diagnose this by invoking 'vlink -h' from a real cmd.exe window, which will pop up a message box with the text "The program can't start because VCRUNTIME140.dll is missing from your computer".

The missing DLL is included in the VC++ 2015 redist (available [here](https://www.microsoft.com/en-gb/download/details.aspx?id=48145)).  Installing it fixes the problem.

**Comment by prb28** [comment]
You're right ! (we should never test on the dev computer !)
I'll add this dll on the next release.
Thanks !

**Comment by DLehenbauer** [comment]
Haha...  Glad I could contribute.  :-)

Now that I have it working, I am *stunned* by what a slick/friction-free experience you've created.  You've done an amazing job!

**Comment by prb28** [comment]
Added to binaries project : https://github.com/prb28/vscode-amiga-assembly-binaries/tree/windows_x64
