### ISSUE TITLE
Regressions with 0.21

### ISSUE THREAD

**Issue by gaoluobe** [prb28/vscode-amiga-assembly#135]
Hello,

First of all, congratulations for your work and a huge thank you!

It seems that the latest release (0.21) on macOS (tested with 10.15.5) has a few regressions based on my testing yesterday.
Once I reverted to the earlier version, I could verify that the issues mentioned were gone.

1. fs-uae-run type configuration isn't recognised anymore. You can reproduce with your workspace example
2. A call to WaitTOF will trigger an exception in the debugger, which is unexpected and was not the case before. See: http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node048B.html . It can be easily tried in your example (with exec base loaded in a6) 

Sorry I don't have screenshots right away because as I said I reverted to the previous version. 
Please, let me know if you have questions and have a nice day !

**Comment by prb28** [comment]
First : Thanks !

- `fs-uae-run`, is replaced by `uae-run`, because it's the same between FS-UAE and WinUAE. I should have made a "Warning" message, sorry about that.

- The exception problem may be that the default exception mask isn't accurate. Can you please try:
   - to unset the exceptions during debugging (to test if it's not a big bug)
   - to change the "exceptionMask" in the launch arguments according to : https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#traps-68000-exception-vector-numbers---source

**Comment by gaoluobe** [comment]
for use-run , understood that makes sense. 

For the exception: First I had no exceptionMask (since this was just introduced). So tried with the one suggested in your example(8188) and got the issue. Also tried with 0 and got also the same issue.
Do you recommend a particular exception mask ?

Here is what I get:
<img width="1009" alt="Screenshot 2021-01-04 at 9 07 44" src="https://user-images.githubusercontent.com/76962944/103560929-7cf89600-4e6d-11eb-9e39-a8aa45a3fd1b.png">

**Comment by gaoluobe** [comment]
Just tried with exceptionMask 11 and it passes. (as it was reported).

Still this is unexpected that I have to set this, should it backward comp with default projects without this ?

**Comment by gaoluobe** [comment]
Some context: many programmers use WaitTOF for setup the reasons mentioned here: http://jvaltane.kapsi.fi/amiga/howtocode/copper.html
It is also used in blueberry setup which is quite popular AFAIK, so I am likely not the only one who will find this. It'd be great if this could part of the "default" mask. At least if no exceptionMask is provided. (Just a suggestion)

**Comment by prb28** [comment]
Yep, you're right, I thought this default value was better... but I was wrong, argh...
I'll set the previous values, after getting all the feedback about the regressions (a coupe of days maybe)...
Do you have a suggestion about a better default mask (different from previous) ?

**Comment by gaoluobe** [comment]
Sorry :( , not sure what's the best mask but I am happy to test any upcoming suggestions.

**Comment by gaoluobe** [comment]
also, just a note about consistency.
fs-uae is still working while fs-uae-run was replaced by use-run, which is fine.
Why not replacing then fs-uae by "uae" and switch automatically based on the platform to fs-uae or winuae ?
Its not a big deal, just an idea...

Anyhow, another suggestion is that when such changes happen, it could be great to preserve temporarily the previous option, make it deprecated with release notes and remove in the version + 2 so that users don't find themselves suddenly with a project that doesn't work anymore. Also not a big problem, just a suggestion if you believe that'd be manageable.

**Comment by prb28** [comment]
You're right for the deprecated option... But well, It's not a corporate product so I make some shortcuts that simplify my code base and optimizes my hobby time...

For the winuae or fs-uae depending on the platform... hum, I think some people prefer fs-uae even on windows or have the two emulators. So no I think they must be separated.

**Comment by gaoluobe** [comment]
Understandable :) . For fs-uae, I wrongly assumed it was just for macOS so that's good as it is indeed. Thanks for your answers !

**Comment by prb28** [comment]
Thinking to keep as default mask : 60 (0b111100 or $3C).
Does it work for you ?

**Comment by gaoluobe** [comment]
Works for me, thanks.

**Comment by prb28** [comment]
ok thanks.
