### ISSUE TITLE
Invalid program to debug error

### ISSUE THREAD

**Issue by Bippym** [prb28/vscode-amiga-assembly#144]
Everything was working fine then suddenly I got the error in the title.i installed the example workspace but error remains. I cannot compile anything. 
![Clipboard Image](https://user-images.githubusercontent.com/21372489/110854038-45163080-82ac-11eb-809a-1540364841f9.jpg)

**Comment by prb28** [comment]
The build looks failed, does the program file exists ?

**Comment by Bippym** [comment]
Yep all sorted :)
