### ISSUE TITLE
Debugging on crash doesn't work

### ISSUE THREAD

**Issue by Bippym** [prb28/vscode-amiga-assembly#151]
If my program crashes, or gives an exception error the program freezes, but I cannot view anything. Registers, memory etc.. not activated, Makes debugging crashes a little harder.

Is it possible when a crash occurs and the exception is raised we can go back and view code?

**Comment by prb28** [comment]
You can activate the exceptions breakpoints in the debugger and maybe change the exception mask : https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#traps-68000-exception-vector-numbers---source
 It won't catch everything, but some of them.
