### ISSUE TITLE
compile-time problems

### ISSUE THREAD

**Issue by hedgehog-nah** [prb28/vscode-amiga-assembly#158]
hello... I have a problem that I can't figure out: basically I have a series of includes, the first include is a startup routine. Looking at the output window, I notice that vlink doesn't link files in the right order. If I remove that particular file that ends up at the top of the linking list, everything works fine. I think it's a bug in vlink.js, someone can give me an explanation and a solution? thank you

**Comment by Real-MJoe** [comment]
I can confirm this. For this reason I use a MAKE file, which I execute with the option "preLaunchTask".

**Comment by hedgehog-nah** [comment]
ok thanks i try ... i was hoping there was a bugfix

**Comment by prb28** [comment]
The vlink call implementation is very naive. It lists all the object files and link it together.
The only thing you can configure is the file containing the entry code (main function) in the vlink configuration _entrypoint_ more info in the wiki: https://github.com/prb28/vscode-amiga-assembly/wiki/Building#vlink
If you need something more specific you should use a _makefile_.

**Comment by hedgehog-nah** [comment]
in fact I noticed that it also compiles the files that I don't include in the main sourc ... really stupid thing ... by chance the assembly order is sometimes random? because sometimes I get strange compilation errors ... I close and reopen vscode and it compiles perfectly.

**Comment by prb28** [comment]
Very strange behavior... with the include and exclude fields you can select the files you want to compile and link.
Maybe there are some old file in the build directory.

**Comment by hedgehog-nah** [comment]
ok i solved with the entrypoint trick... thanks a lot for the support... and thank you for the work you do

**Comment by prb28** [comment]
Great! Thanks.
