### ISSUE TITLE
Mega Drive\Genesis Support

### ISSUE THREAD

**Issue by RetroRusty** [prb28/vscode-amiga-assembly#163]
Hi,

I know this extension is for the Amiga, but can it be used to code assembly for the SEGA Mega Drive\Genesis?

Thanks

**Comment by prb28** [comment]
Hi,

If it is a Motorola 68000 assembly, yes you can use it as a syntax coloring and formatting tool. You'll have access to the assembly documentation too.
You would not be able to debug and run it, and maybe some amiga info for registers will be annoying.
