### ISSUE TITLE
Able to change the filename from GENCOP

### ISSUE THREAD

**Issue by phaze101** [prb28/vscode-amiga-assembly#164]
Hi, it would be great if one would be able to change the filename from gencop when using the example file. It should take the filename from the current tab Window.

**Comment by prb28** [comment]
Maybe  a function to set the name of the binary with a field to write the new name would be better ?

**Comment by Real-MJoe** [comment]
My solution is to use task.json over the **preLaunchTask** parameter of launch.json.  There the current file of the selected tab can be compiled and debugged easily :)  I use the ${file} variable.

![grafik](https://user-images.githubusercontent.com/40276633/139720820-1b1c3eca-5863-4808-8758-62537fe3f064.png)

**Comment by phaze101** [comment]
Hi, yes I know you can use ${file} but I do not know enough about the preLaunchTask is it possible to share @Real-MJoe

**Comment by Real-MJoe** [comment]
Of course I share my config, but the paths still need to be adjusted accordingly.

**launch.json**
![grafik](https://user-images.githubusercontent.com/40276633/139797137-c31f7ecf-c8ec-402d-b232-bda971aac513.png)

task.json
![grafik](https://user-images.githubusercontent.com/40276633/139797183-a8145c04-639a-4844-847c-fe4ac7f76362.png)

**Comment by phaze101** [comment]
thank you will definitely try it out.
