### ISSUE TITLE
Not work: Right click to add a memory dump in the watch window

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#174]
Unfortunately, the new "Right click to add a memory dump in the watch window" feature does not work. I don't see the menu item "Add to Watch" when I am in debug mode. I use the addin in version 1.0.

**Comment by prb28** [comment]
To enable this option you have to select the text in the editor and right click after. 
Can you try this ?

**Comment by Real-MJoe** [comment]
Sorry, I didn't know I had to select the text first.

**Comment by prb28** [comment]
It's the default way of vscode. I thought at first that it was weird too...
Can please you confirm it works for you ?

**Comment by Real-MJoe** [comment]
Das Feature funktioniert wie es soll. Also kann der Bugreport geschlossen werden. Entschuldigen Sie bitte meine Unwissenheit.
