### ISSUE TITLE
Create ADF with defined Bootblock not work

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#178]
Since version 1.x no ADF can be created with a defined bootblock code. The following error is displayed:
![grafik](https://user-images.githubusercontent.com/40276633/146594679-40b32326-2700-40e7-b837-271ff8a03db7.png)

The parameters to compile the bootblock look funny. Unfortunately I cannot change them.
![grafik](https://user-images.githubusercontent.com/40276633/146594841-ec485b58-bad8-4ee5-856d-ac7b0da3d417.png)

Thanks in advanve.

Edit: Tested with Version 1.0.0 and 1.1.0.

**Comment by prb28** [comment]
Here is the fix : https://github.com/prb28/vscode-amiga-assembly/releases/download/pre_1.1.0_1/amiga-assembly-1.1.0.vsix
I've updated the wiki : https://github.com/prb28/vscode-amiga-assembly/wiki/ADFTools

**Comment by Real-MJoe** [comment]
Thanks for the fix. Now it works as it should. :)
