### ISSUE TITLE
Fresh install and issues with winuae

### ISSUE THREAD

**Issue by Bippym** [prb28/vscode-amiga-assembly#196]
So I have completed a fresh install of v1.14. I have assigned my roms folder for winuae. Whenever I run winuae I get an error saying there is no disk present in DH0.

This is with both a500 and a1200 quickstart configs.

The installed version of WinUAE is 4.9.0

I haven't made any changes. FSUAE seems to work as intended

**Comment by prb28** [comment]
You already found that it was discussed here :  http://eab.abime.net/showthread.php?p=1527216#post1527216.
The problem is the use of you standard winuae configuration in replacement of the on needed for the extensions.

You'll have to change the launch parameters, in your .vscode/launch.json try to add these options :

```json
"-f",
"./default.uae",
```

The result will look like :
```json

        {
          "type": "winuae",
          "request": "launch",
          "name": "WinUAE Debug",
          "stopOnEntry": true,
          "serverName": "localhost",
          "serverPort": 2345,
          "startEmulator": true,
          "trace": false,
          "exceptionMask": 8188,
          "emulatorStartDelay": 1500,
          "emulator": "${config:amiga-assembly.binDir}/winuae.exe",
          "emulatorWorkingDir": "${config:amiga-assembly.binDir}",
          "program": "${workspaceFolder}/uae/dh0/gencop",
          "options": [
                      "-f",
                      "./default.uae",
                      "-s",
                      "quickstart=a500,1",
                      "-s",
                      "filesystem=rw,dh0:${workspaceFolder}/uae/dh0",
                      "-s",
                      "debugging_trigger=SYS:gencop",
                      "-s",
                      "debugging_features=gdbserver"
                      ],
          "preLaunchTask": "amigaassembly: build"
        }
```

**Comment by phaze101** [comment]
@prb28 I have seen this personally on Windows 11 WinUAE is behaving strangely. @Bippym shared his screen with me to see the issue. There is definitely something weird going on. The extension seems fine but not the WinUAE that gets installed with the extension. We tested Ver 1.0 of the extension and it behaved the same on Windows 11.

**Comment by prb28** [comment]
Ok, I have to install w11 in a vm to try to see and debug it.

**Comment by prb28** [comment]
@Bippym Thanks for this video.
Yes I agree with you, maybe there is some security limitation with w11 and the C:/ drive.
It also can be this "../../../.." path that is too long. When you use your desktop you have a nearest path so maybe it stays under the 256 chars. (I don't know why winuae does this, certainly a question for Toni).
You can try to enable long paths : https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd 
I've started a download of w11 to create a vm and try it. But it will take me some time.

**Comment by prb28** [comment]
https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10

**Comment by Bippym** [comment]
My path is

C:/development/test/

Definitely not a long path.

**Comment by prb28** [comment]
Yes I agree, but I was wondering if winuae, as you noted, uses relative paths.
From here:
```
c:\Users\Bippy\AppData\Roaming\Code\User\globalStorage\prb28.amiga-assembly\file-downloader-downloads\vscode-amiga-assembly-binaries-@-1.1.4\vscode-amiga-assembly-binaries-windows_x64\winuae.exe
```
You will have : 
```
c:\Users\Bippy\AppData\Roaming\Code\User\globalStorage\prb28.amiga-assembly\file-downloader-downloads\vscode-amiga-assembly-binaries-@-1.1.4\vscode-amiga-assembly-binaries-windows_x64\../../../../../../../../../../../C:/development/test/uae\dh0\s\startup-sequence
```
It is 264 characters.

**Comment by Bippym** [comment]
Yeah, i follow now. Worth asking Toni

**Comment by prb28** [comment]
I've just finished my vm in windows 11, I did reproduce it with the path "C:/development/test/".
Modifying the regexp to active the long path as in page: https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10 resolves the issue.

Folder: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
key: LongPathsEnabled 
Value: 1

**Comment by prb28** [comment]
The worst thing about this .... it that I already had it in the FAQ (I feel dumb...).
https://github.com/prb28/vscode-amiga-assembly/wiki/FAQ#the-emulator-starts-but-it-does-not-boot

**Comment by Bippym** [comment]
That's great. Is it possible to make thr registry change when installing the extension?

**Comment by prb28** [comment]
Maybe, but I won't mess with the user registry when he uses the extension.
So maybe I'll shorten a bit the download path but it's just hiding the issue a bit.
The real solution would come from winuae binary.
