### ISSUE TITLE
Unable to load segments

### ISSUE THREAD

**Issue by Vagant1** [prb28/vscode-amiga-assembly#198]
Hi,

I was using the same workspace without any changes and I now have the message when trying to dun debugging on FS-UAE 'Unable to lad segments'. Any idea what could be the reason?

**Comment by prb28** [comment]
If you are on Windows, it can be related to long paths : https://github.com/prb28/vscode-amiga-assembly/wiki/FAQ#the-emulator-starts-but-it-does-not-boot
If not maybe it's a naming problem or a case sensitivity one.

**Comment by Vagant1** [comment]
It’s MacOS and FA-UAE. Will try to find the problem.

**Comment by prb28** [comment]
You can zip and send me a download link and I'll try it on my Mac.

**Comment by igorminic** [comment]
I have the same exact issue on MacOS and FA-UAE.

@Vagant1 could you explain what you did to fix it?

Tnx!

**Comment by Vagant1** [comment]
I am sorry I don't think it will be helpful but I deleted the whole workspace and created again and it just worked. 
Didn't do anything specific.
