### ISSUE TITLE
custom configurations uae

### ISSUE THREAD

**Issue by hedgehog-nah** [prb28/vscode-amiga-assembly#204]
hello, I'm looking for a way to launch winuae with custom configurations
I tried in various ways but don't work
this is for example my last configuration I edited in settings.json, what am I wrong?

"configurations": [
        {
            "type": "uae-run",
            "request": "launch",
            "name": "WinUAE Run 060",
            "buildWorkspace": true,
            "emulator": "${workspaceFolder}/bin/winuae.exe",
            "emulatorWorkingDir": "${workspaceFolder}/bin",
            "options": [
                "-s",
                "-f=${workspaceFolder}/bin/a1200_060.uae",
                "-s",
                "filesystem=rw,dh0:${workspaceFolder}\\uae\\dh0"
            ]
        },

**Comment by Real-MJoe** [comment]
My config looks like this:
![grafik](https://user-images.githubusercontent.com/40276633/153019509-376efc4c-6e91-4b2d-b5b3-b851cbe5a054.png)

**Comment by hedgehog-nah** [comment]
> My config looks like this: ![grafik](https://user-images.githubusercontent.com/40276633/153019509-376efc4c-6e91-4b2d-b5b3-b851cbe5a054.png)

thanks it works fine :)
