### ISSUE TITLE
Debugger not activating

### ISSUE THREAD

**Issue by Bippym** [prb28/vscode-amiga-assembly#205]
I am including files and find the debugger isn't activating when a breakpoint is placed in any included file except my main.asm (which is included itself).

See the following video
https://youtu.be/e5w0bJveOvU

**Comment by prb28** [comment]
You have a build error in you main file. I think the new binary is not linked so you are debugging the old program.
Try to delete the executable file and build again. I think you would not have a new file created.

**Comment by Bippym** [comment]
I already had deleted them. The errors are shown below, and if I compile again immediately the errors clear.. Go figure

I also don't know why I get random relocation errors

![image](https://user-images.githubusercontent.com/21372489/153297776-9c8f7468-28dd-4e9a-aee8-ee3035ada4e2.png)

**Comment by prb28** [comment]
There are two sources for errors : vasm and vlink.
When you edit vasm the extension only runs a vasm compilation on the file and shows the errors -> no error in your case.
When you run your program the extension compiles the files with vasm and link them with vlink. You can have vlink errors during this build. these are the errors you are seeing in you screen shot. If vlink has error, you will not have a new executable.

**Comment by Bippym** [comment]
I am getting a new executable. I deleted everything from the build folder and my main exe from dh0.

Let me know if you need my source, and a place to send it. I don't necessarily want it made public. It is Diiiirty

**Comment by prb28** [comment]
Yes, if you can send me the sources that will help. I've tried modifying the example and adding sources and it worked.
You can send me it by pm on eab, discord or mail.

**Comment by Bippym** [comment]
What's your discord name? Are you in any of the Amiga den groups?

**Comment by prb28** [comment]
Prb28#3764, I'm on the amigadev group.

**Comment by prb28** [comment]
Fixed in 1.3.1 pre-release.
