### ISSUE TITLE
Where is the "Build" button on the bottom bar of VSCode ??

### ISSUE THREAD

**Issue by dek-project** [prb28/vscode-amiga-assembly#209]
Hi...
in previous version, I had a "Build" button on the bottom bar of VSCode, and now this button seems to have gone...
I know there is a shortcut (ctrl-shift-b) but this button was in fact very usefull for me... any idea why I cannot see it anymore ??

**Comment by prb28** [comment]
It's done in the example workspace, you can try it following this : https://github.com/prb28/vscode-amiga-assembly/wiki/Getting-started#example-workspace
Add a *preLaunchTask* option in the *launch.json* configuration, see: https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#example-for-fs-uae
