### ISSUE TITLE
Unable to Download Binaries

### ISSUE THREAD

**Issue by timcal1968** [prb28/vscode-amiga-assembly#211]
I've tried this extension on Windows 11 and also with Mac OS, and with both versions it will not download the binaries. It tries to start then pops up with an error message:

The "streams" argument must be specified.

Edit:
After a lot of playing around, the problem appears to be with the latest version of VSC 1.66 as I've just tried a few older versions of VSC which seem to be fine.

Kind regards, Tim

**Comment by prb28** [comment]
You're right, there something wrong with the latest vscode.
I'm debugging...

**Comment by prb28** [comment]
Relates to https://github.com/microsoft/vscode-file-downloader/issues/31
And https://github.com/microsoft/vscode/issues/144962

**Comment by prb28** [comment]
As a workaround on windows, but should be similar on other platforms.

Download the binaries:

- windows: https://github.com/prb28/vscode-amiga-assembly-binaries/archive/refs/tags/1.2.0-windows.zip
- mac: https://github.com/prb28/vscode-amiga-assembly-binaries/archive/refs/tags/1.2.0-osx.zip
- linux: https://github.com/prb28/vscode-amiga-assembly-binaries/archive/refs/tags/1.2.0-debian.zip

Unzip it (as an example in: "c:/mybinaries").
You should have the file c:/mybinaries/fs-uae.exe

Download the example project
- https://github.com/prb28/vscode-amiga-wks-example/archive/refs/tags/1.0.0.zip

Unzip it (as an example here: c:/myproject)

Add file 'c:/myproject/.vscode/settings.json' with:
```json
{
    "amiga-assembly.binDir": "c:/mybinaries"
}
```

And it should be good to go.

**Comment by timcal1968** [comment]
Thanks for taking the time to look into it! Once I realised the problem was specific to the latest version of VSC, I just left the older version installed as I managed to download the binaries that way. I’m guessing it won’t try and download them again now that I have them if I accidentally upgrade?

Kind regards, Tim.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prb28** [comment]
If you download a new version of the extension the binaries will be updated, and the bug will still be there.
But I won't release anything unless I've a solution for this issue. That would bring too much trouble.

**Comment by timcal1968** [comment]
Thanks for clarifying the situation. I’ll just stick with an older version of VSC for the time being!

Kind regards, Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prb28** [comment]
Fix for the download extension:
[file-downloader-1.0.12.zip](https://github.com/prb28/vscode-amiga-assembly/files/8405823/file-downloader-1.0.12.zip)

**Comment by timcal1968** [comment]
Awesome, many thanks for looking into the problem and sorting so quickly!

**Comment by prb28** [comment]
Fixed in pre-release 1.3.2 -> future release 1.4
