### ISSUE TITLE
Build multiple folders

### ISSUE THREAD

**Issue by juusu** [prb28/vscode-amiga-assembly#213]
I haven't used the extension in a while and coming back to it noticed that my workspace files no longer work since you've moved to tasks.

I used to have my projects structured in multiple folders, for example I have a "replay/" folder with my music player, and another "intro/" folder with some code using the replayer

I don't use includes, but have XDEF / XREF everywhere and have vlink take care of everything.

I had both folders added to my workspace, like so:

	"folders": [
		{
			"path": "..\\"
		},
		{
			"path": "..\\..\\replay"
		}
	],
	
and clicking "Build" would assemble everything in both folders and the linker would do its magic.

Now I can't get it to do the same using build tasks, it only seems to build files in the folder where the entrypoint is, and doesn't "see" other folders in my workspace.  I'm getting "undefined symbol" errors and naturally the build fails.

How can I get it to build all the folders in my workspace again?

**Comment by prb28** [comment]
You can try to set the includes options of vlink as:

"includes": "**/*.{s,S,asm,ASM}",

Not sure it's enough, I'll try it later if it doesn't work.

**Comment by juusu** [comment]
Thanks for the quick response!

Your suggestion doesn't seem to work :(

However, I managed to get it to do what I want using something like:

"includes": "../{intro,replay}/*.{s,S,asm,ASM}"

but it would be nice for it to be able to pick up all the folders in the workspace automatically.

I can also do:

"includes": "../**/*.{s,S,asm,ASM}"

but that will also pick up other code present in the same parent folder which I don't want assembled as part of the project/workspace.

**Comment by prb28** [comment]
You can mix with the exclude option.
But I understand your point to just add the folder to the workspace.

**Comment by prb28** [comment]
fixed in pre-release 1.3.3.
