### ISSUE TITLE
The Create Example Workspace Fails

### ISSUE THREAD

**Issue by Yazwh0** [prb28/vscode-amiga-assembly#214]
I get the error:
The "streams" argument must be specified

Output windows do not suggest a problem, 
[info] Selected folder: file:///d%3A/Documents/Source/amigatest and program name: amitest
[info] Downloading workspace version 1.2.0 to folder file:///d%3A/Documents/Source/amigatest

**Comment by prb28** [comment]
It is fixed in the pre-release version.
Please select the prs-release in the extension page in vscode and try again after the installation.

**Comment by Yazwh0** [comment]
yes ,sorry, just found that, thanks!
