### ISSUE TITLE
Making the debugger work as a standalone component? 

### ISSUE THREAD

**Issue by themkat** [prb28/vscode-amiga-assembly#218]
Seems to me like it would be possible to make the debugger work as a standard Debug Adapter Protocol component, and therefore be usable in other editors. The only blocker I can see would be that it depends on the vscode module a lot, which would not exist when running outside of VSCode. (I tried quickly just making webpack build a js-file for it and run it with node). Would be nice if I could use it in Emacs (through dap-mode) 🙂  My question is: would you accept a PR to make that possible? And is there anything you can think of that would stop it from happening? If it is already possible, please let me know. Could not find anything when I looked around. 

Yes, many VSCode extensions already do something like this. VSCode Ruby, Native Debug etc. comes to mind.

**Comment by prb28** [comment]
It's a great idea.
It looks like a lot of work to do, but if you are motivated, of course I'll accept a PR!
I don't think something will bloc this, as you said it's used in others extensions. But I don't know how the DAP works.

**Comment by themkat** [comment]
@prb28 Nice! 🙂  Haven't had the time to look at it yet anyway. If his version does what I need, I may contribute to it, and then make the necessary dap-mode config for Emacs.
