### ISSUE TITLE
Cannot launch example program in Linux

### ISSUE THREAD

**Issue by cbmeeks** [prb28/vscode-amiga-assembly#228]
It took me a while to figure out how to run the example setup on my Fedora system.  But when I finally got around to launching a program I compiled, I'm getting a connection refused on FS_UAE.  

![image](https://user-images.githubusercontent.com/49341/178344866-e5db5ae7-daa3-4f0c-81a7-7c9abf6d7a49.png)

Here is my launch.json:
      
      {
          "version": "0.2.0",
          "configurations": [
              {
                  "type": "fs-uae",
                  "request": "launch",
                  "name": "FS-UAE Debug",
                  "stopOnEntry": true,
                  "serverName": "localhost",
                  "serverPort": 6860,
                  "trace": false,
                  "startEmulator": true,
                  "windows": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae.exe"
                  },
                  "osx": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae"
                  },
                  "linux": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae"
                  },
                  "emulator": "${config:amiga-assembly.binDir}/fs-uae",
                  "emulatorWorkingDir": "${config:amiga-assembly.binDir}",
                  "program": "${workspaceFolder}/uae/dh0/Robocop",
                  "options": [
                      "--chip_memory=2048",
                      "--hard_drive_0=${workspaceFolder}/uae/dh0",
                      "--joystick_port_1=none",
                      "--amiga_model=A1200",
                      "--remote_debugger=200",
                      "--use_remote_debugger=true",
                      "--automatic_input_grab=0"
                  ],
                  "preLaunchTask": "amigaassembly: build"
              },
              {
                  "type": "uae-run",
                  "request": "launch",
                  "name": "FS-UAE Run",
                  "windows": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae.exe"
                  },
                  "osx": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae"
                  },
                  "linux": {
                      "emulator": "${config:amiga-assembly.binDir}/fs-uae"
                  },
                  "emulator": "${config:amiga-assembly.binDir}/fs-uae",
                  "emulatorWorkingDir": "${config:amiga-assembly.binDir}",
                  "options": [
                      "--chip_memory=2048",
                      "--hard_drive_0=${workspaceFolder}/uae/dh0",
                      "--amiga_model=A1200",
                      "--automatic_input_grab=0"
                  ],
                  "preLaunchTask": "amigaassembly: build"
              }
          ]
      }

Here is my tasks.json:

      {
          "version": "2.0.0",
          "tasks": [
              {
                  "type": "amigaassembly",
                  "vasm": {
                      "enabled": true,
                      "command": "${config:amiga-assembly.binDir}/vasmm68k_mot",
                      "args": ["-m68000", "-Fhunk", "-linedebug"]
                  },
                  "vlink": {
                      "enabled": true,
                      "command": "${config:amiga-assembly.binDir}/vlink",
                      "includes": "*.{s,S,asm,ASM}",
                      "excludes": "",
                      "exefilename": "../uae/dh0/Robocop",
                      "entrypoint": "Robocop.s",
                      "args": ["-bamigahunk", "-Bstatic"]
                  },
                  "problemMatcher": [],
                  "label": "amigaassembly: build",
                  "group": {
                      "kind": "build",
                      "isDefault": true
                  }
              },
              {
                  "type": "amigaassembly",
                  "vasm": {
                      "enabled": true,
                      "command": "${config:amiga-assembly.binDir}/vasmm68k_mot",
                      "args": ["-m68000", "-Fhunk", "-linedebug"]
                  },
                  "vlink": {
                      "enabled": true,
                      "command": "${config:amiga-assembly.binDir}/vlink",
                      "includes": "*.{s,S,asm,ASM}",
                      "excludes": "",
                      "createStartupSequence": true,
                      "createExeFileParentDir": true,
                      "exefilename": "../uae/dh0/Robocop",
                      "args": ["-bamigahunk", "-Bstatic"]
                  },
                  "problemMatcher": [],
                  "label": "amigaassembly: build"
              }
          ]
      }

My system is Fedora 36 with GNOME 42 (Wayland).  I can run FS_UAE Launcher just fine.

Any ideas what I'm doing wrong?

Thanks

**Comment by prb28** [comment]
In the settings you'll find the path to the downloaded binary dir.
Try to run fa-use in a shell from this directory.

**Comment by cbmeeks** [comment]
Launching from the bin folder seems to work.

![image](https://user-images.githubusercontent.com/49341/178355593-c4398eec-340f-40ac-b9ac-9a2673ac6290.png)

**Comment by prb28** [comment]
Ok, try to add the option emulatorStartDelay in the launch settings. Set it to 20000, it's in me so it will wait 20s.
https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#parameters

**Comment by cbmeeks** [comment]
Seems to have no affect at all.  In fact, the emulator starts up without any delay.
I even changed it to 200,000 and nothing was different.

**Comment by cbmeeks** [comment]
Also, do I have to put the Amiga ROMS in the bin folder?  Sorry, I'm just learning FS-UAE.

**Comment by prb28** [comment]
Yes you may have to open the socket port on the firewall or change it because this port may be used or reserved.
Try to set a 55555 port for the debugger and fs-uae.

**Comment by cbmeeks** [comment]
Same thing.  Denied.

I looked at adding the 6860 port explicitly and was told it was already there:

![image](https://user-images.githubusercontent.com/49341/178489094-324f22f4-2422-4420-9dab-64f38c9ac6fd.png)

**Comment by prb28** [comment]
I'm far from a computer for a couple of weeks, I'll try on a vm as soon as possible. Which version of fedora do you use ?

**Comment by cbmeeks** [comment]
Any help is appreciated.

![image](https://user-images.githubusercontent.com/49341/179310650-6af9e79e-8435-4e2e-8f72-85af8caa699f.png)

**Comment by prb28** [comment]
It works on a fresh install of fedora 36 in virtual box:
![image](https://user-images.githubusercontent.com/10462286/181662638-33a29e17-a9c2-4bcf-9bc5-dd3d62534ff6.png)

I had to install openal to launch fs-uae (I don't think it's your issue):
`sudo dnf install openal`

There is definitely something blocking port 6860 in your install, maybe a firewall or a service.

**Comment by cbmeeks** [comment]
FYI,

I don't know what changed but this is now working.  On a whim I came back to this and created a new project and it worked first time.
