### ISSUE TITLE
Downloading binaries

### ISSUE THREAD

**Issue by Private-Storm** [prb28/vscode-amiga-assembly#244]
Well when trying to download the binaries after installing your extension I run into the following:

**command 'amiga-assembly.clean-downloaded-binaries' not found.** 

MACOS 
12.6

Extension
1.7.1

VSCode
1.72.2

**Comment by prb28** [comment]
Do you have another amiga extension installed ?

**Comment by Private-Storm** [comment]
No I've double checked its the only extension so far.

**Comment by prb28** [comment]
I think I understand the issue. The extension may not be well initialized if you do not open a ".s" file. 
Can you try : 

- Type F1
- type : Amiga Assembly: Download binaries
- wait for the download to end 
- create an example workspace

**Comment by Private-Storm** [comment]
Well this time it seems to work. I've got a window (downloading binaries...) creating a new example workspace debugging & running seems fine now.

**Comment by prb28** [comment]
Ok, thanks, I'll add a fix in next release.

**Comment by Private-Storm** [comment]
You're welcome and really nice work thank you!
