### ISSUE TITLE
VASM args used when assembling per file (on save) should be consistent with the ones passed in tasks.json

### ISSUE THREAD

**Issue by gaoluobe** [prb28/vscode-amiga-assembly#245]
_Finally upgraded from very old version to the latest:)...really amazing work there..._ 
It looks that default build args are located here: https://github.com/prb28/vscode-amiga-assembly/blob/master/src/vasm.ts#L40
How can I override them when assembling files on save, incrementally ("command-s"). 
I need the args of the "default build" to be consistent with the ones I pass in the task (which has property "isDefault":true)
Thanks for your help

**Comment by prb28** [comment]
Here is the wiki link that may help you : https://github.com/prb28/vscode-amiga-assembly/wiki/Building#changing-the-build-options-for-syntax-checking

**Comment by gaoluobe** [comment]
oh thanks, sorry I missed this. I needed "amigassembly: compile current file". 
As a side remark: Redefining parameters indeed works there, I feel like while it is more flexible it is also quite redundant for my case. Not sure why anyone would like different args depending on doing one file assembling or not.

**Comment by gaoluobe** [comment]
Closing now, and thanks again for the quick answer.

**Comment by prb28** [comment]
I agree, here is the talk about the rework needed of the build / run / debug arguments: https://github.com/prb28/vscode-amiga-assembly/discussions/236
