### ISSUE TITLE
VSCode 1.74.x  highlighting problem

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#247]
Unfortunately, in the current version VSCode 1.74.x almost every line is marked as an error. However, the source code can be compiled without errors.
Here is an example:
![grafik](https://user-images.githubusercontent.com/40276633/209116666-bdebfdd4-916d-4c9b-b061-7be3aaf74e85.png)

**Comment by prb28** [comment]
Do you have a specialized configuration as : https://github.com/prb28/vscode-amiga-assembly/wiki/Building#changing-the-build-options-for-syntax-checking ?

**Comment by Real-MJoe** [comment]
Die Fehler werden gleich nach dem Starten von VSC bzw. nach dem öffen eines Workspace angezeigt. 

Das "Video" ziegt das Festlegen von Parameter für das Ausführen von vasm.

**Comment by Real-MJoe** [comment]
I have found the problem. The extension "	
Amiga C/C++ Compile, Debug & Profile" is to blame. After I deactivated this for the project, no "Live Syntax Check" is executed anymore. 
Thanks for the help and have a nice christmas.

**Comment by prb28** [comment]
Yes as we work on the same files the two extensions can't ne activated the same time.
Merry Christmas!
