### ISSUE TITLE
command 'amiga-assembly.disassemble-file' not found after update

### ISSUE THREAD

**Issue by Eternal-student** [prb28/vscode-amiga-assembly#25]
Hi, I just updated to v0.9.0 and I'm getting the below error when trying to use the supplied binaries
command 'amiga-assembly.disassemble-file' not found
The path is the same as when I had it for v0.8.0 which didn't bring up this error message
(although I haven't managed to disassemble any Amiga code yet.. which I think is because I don't know what I'm doing exactly :) )

**Comment by prb28** [comment]
Hi, the first purpose of this extension is to discover the amiga assembly, so you are welcome!
This error is weird, could you try to uninstall the extension, restart vscode and install it again?
What is you OS ? I will try to reproduce it tonight.

**Comment by Eternal-student** [comment]
Ok I'll have an experiment.  This was in Windows and I'd set it up on my desktop (v0.8.0) and I think it was working to the point it was able to find the cstool file.  I then tried to set it up on my laptop a couple of days later (v0.9.0) and I couldn't get it to work (came up with the above error message).. I then updated my desktop to v0.9.0 and I also got the above error.
Now I've tried to reinstall v0.8.0 and I can't get it to reference the file either!  So maybe it's something I'm doing wrong.. I'll play around with it and let you know.  Don't waste your time on it unless I'm sure it's not something I'm doing wrong!

**Comment by prb28** [comment]
I’ve tried with windows 7 and 10 and it seemed ok.
This error tells that the function declared ont the package file description is not found.

Do you use the windows ‘user’ install of vscode ?
Which version of vscode do you have ?

**Comment by prb28** [comment]
;-)

**Comment by prb28** [comment]
I hope that the new installation will fix this.

**Comment by Eternal-student** [comment]
Right, I'm really sorry, I've found what I was doing wrong.  I think I copied the settings from the DEFAULT USER SETTINGS to the USER SETTINGS rather than the WORKSPACE SETTINGS.  I can see that now in the Wiki instructions.  Once again apologies. (although I'm not sure how I had it working and then after updating not.. it was the first time I set it up so possibly I followed the instructions properly but then changed something)
By the way, if I had another simple newbie question, is there a good place to ask it? :p

**Comment by prb28** [comment]
In the last version I've touched the settings management, after an issue on workspace settings in vscode. So It certainly did something unexpected in your configuration.
There is no really place for questions in github... The best is to fill a new issue it may be useful for someone else !

**Comment by Eternal-student** [comment]
Ok brilliant thanks for the quick response (and great looking vscode plugin).. if my next question is really obvious feel free to delete it!

**Comment by prb28** [comment]
I reproduced this issue.
To activate the extension, it is needed to open an assembly file ".s".
So if you choose "Amiga Assembly: disassemble" file from the menu before opening ".s" file you get this error.
