### ISSUE TITLE
Binaries not marked as executable on macOS after update 1.6.0 -> 1.8.0

### ISSUE THREAD

**Issue by cobour** [prb28/vscode-amiga-assembly#257]
After updating the extension from 1.6.0 to 1.8.0 on macOS 13.2.1 and VSC 1.76.1 the executables (now in folder "~./vscode/extensions/prb28.amiga-assembly-1.8.0/resources/bin/darwin") did not have the necessary x flag.
As a consequence all builds did not produce output.

I had to issues these commands in the folder of the executables to make it work again:
chmod 755 adf*
chmod 755 v*

**Comment by prb28** [comment]
Thanks for the issue and the workaround.
This is fixed in 1.8.1.
