### ISSUE TITLE
Link order cannot be set

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#259]
First of all, many many thanks for the further development on the extension, to all involved. 
Unfortunately, the new version 1.8.1 has two major problems, the first of which has been present for some time.

### Problem 1:
The files are compiled in the wrong order than I specify. This has unwanted side effects or I want to determine the order deliberately. Until now I had to use a MAKE file for this.

The three files "main.s", asset.s, and startup.s must be compiled in the order "main.s, startup.s, asset.s". In the "main.s" is also the entrypoint. I can set this with the entrypoint switch in task.json.  

Unfortunately the files are sorted by name.
Here times the vlink setting:
![grafik](https://user-images.githubusercontent.com/40276633/226588077-c022902d-d159-4413-bf27-3e9ead61e77e.png)

Compiling and linking looks like this:
![grafik](https://user-images.githubusercontent.com/40276633/226588138-597946d1-e737-4303-bb17-788130540355.png)
and
![grafik](https://user-images.githubusercontent.com/40276633/226588202-71b8a2c8-beba-4aba-956f-4913d12007ff.png)

**Compile errror!**

If you add a sort-prefix to the files, the files will also be sorted, but according to my wish.

Here is the vlink setting:
![grafik](https://user-images.githubusercontent.com/40276633/226588455-a71a57a3-f859-4a56-9e61-040c17653e1c.png)

Compiling and linking looks like this:
![grafik](https://user-images.githubusercontent.com/40276633/226588507-5372bb48-e9e9-4936-9d56-0135861a5a85.png)
and
![grafik](https://user-images.githubusercontent.com/40276633/226588575-a3473bdc-f988-48d6-a46c-204c1032fd6e.png)

**All fine now!**
_Workspace_ [IssueDebugging_(1.8.1).zip](https://hoffer-industries.com/tmp/IssueDebugging_(1.8.1).zip)

### Problem 2
The bigger problem is the handling of breakpoints. These are set incorrectly or not triggered at all. 
If you start the project and end up in the debugger ("stopOnEntry": true) and then press F11 to continue to the InitSystem jump, the "function" from the startup.s file is not displayed, but a wrong position in the main.s file.
![grafik](https://user-images.githubusercontent.com/40276633/226589358-c178f22d-50fd-4988-aa07-9de261ed80dc.png)

If you set a breakpoint in the files asset.s on the function AllocAssetMem, it is not triggered.

The problem does NOT exist with version 1.6, in which the code can be stepped through and debugged properly.
![grafik](https://user-images.githubusercontent.com/40276633/226589389-20633ec8-8cba-40fb-b0a4-56f9a6ced978.png)

_Workspace_ [IssueDebugging_(1.6).zip](https://hoffer-industries.com/tmp/IssueDebugging_(1.6).zip)

Many greetings

**Comment by prb28** [comment]
@Real-MJoe, I split this issue in 2, more easy for us to follow.
