### ISSUE TITLE
Breakpoint not hit and stepping in function not correct

### ISSUE THREAD

**Issue by prb28** [prb28/vscode-amiga-assembly#260]
The bigger problem is the handling of breakpoints. These are set incorrectly or not triggered at all.
If you start the project and end up in the debugger ("stopOnEntry": true) and then press F11 to continue to the InitSystem jump, the "function" from the startup.s file is not displayed, but a wrong position in the main.s file.
grafik

If you set a breakpoint in the files asset.s on the function AllocAssetMem, it is not triggered.

The problem does NOT exist with version 1.6, in which the code can be stepped through and debugged properly.
grafik

Description in https://github.com/prb28/vscode-amiga-assembly/issues/259

**Comment by prb28** [comment]
@grahambates Can you please look at this on ?

**Comment by grahambates** [comment]
Yeah sure. I can reproduce the issue. I'll have a go at fixing it tomorrow.
