### ISSUE TITLE
 Link order cannot be set (Bug partly still present)

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#262]
Thanks for fixing the bug. The first part also works correctly. The given data are compiled according to their order in task.json. :)
![grafik](https://user-images.githubusercontent.com/40276633/227487210-04b291d4-d2dc-4cbe-9af1-37060cdf144f.png)

Unfortunately, the order in the link process is still sorted by the names of the files. The entrypoint is at the first place which is correct, but the startup.o file must be linked before the asset.o file. 
![grafik](https://user-images.githubusercontent.com/40276633/227487477-e6529f07-30a1-4c1a-90b0-5bc80e508a4c.png)

Thanks for the efforts

**Comment by prb28** [comment]
Sorry about that, I was overconfident with my little unit test.
Thanks for the report !

**Comment by prb28** [comment]
@Real-MJoe can you please try th 1.8.3 pre-release ?

**Comment by Real-MJoe** [comment]
Yes... the bug is fixed in this pre-release. Thanks for fixing the problem quickly.
