### ISSUE TITLE
[QUESTION] Does this  Amiga 68k Syntax-Highlighter is also useful for 68k Sega Genesis?

### ISSUE THREAD

**Issue by Axis4s** [prb28/vscode-amiga-assembly#268]
Since this is a 68k Assembly highlighter does this mean this extension is useful for megadrive asm programming?

**Comment by prb28** [comment]
Well... for editing, yes, maybe some overlays for amiga documentation may bother you, but not that much.
To build, you can add some tasks with your makefile or vasm commands and options (don't know if vasm/vlink can produce a binary for this platform).
For running, you can create a custom task to start the emulator.
For debugging, there is no way to do it without an emulator modification.
