### ISSUE TITLE
File type Amiga assembly marks syntax errors that are not syntax errors

### ISSUE THREAD

**Issue by swissdude15** [prb28/vscode-amiga-assembly#269]
![image](https://github.com/prb28/vscode-amiga-assembly/assets/134631577/058f432c-eb9a-4ac6-9394-9894fa5726a6)

The file type Amiga assembly (m68k) marks syntax errors which are none, see screenshot. Concerns plugin version 1.8.2 under Visual Code 1.78.2, Windows 11.

**Comment by Real-MJoe** [comment]
This sounds like the same [problem](https://github.com/prb28/vscode-amiga-assembly/issues/247), which is not one.

**Comment by swissdude15** [comment]
Yes, that is correct. As soon as I deactivate the Amiga C/C++ plugin, the problems mentioned above are no longer present. Thanks for the hint!
