### ISSUE TITLE
When debuging it lounching fu-uae to run the program

### ISSUE THREAD

**Issue by C64HexCoder** [prb28/vscode-amiga-assembly#272]
The debugger does not work. instead of debgging it launch the program.

**Comment by prb28** [comment]
Which os do you use?
Did you try with the sample project?

**Comment by C64HexCoder** [comment]
Windows 11. No, i tryed with all my amiga programs and created a new one
for testing.

בתאריך יום א׳, 10 בספט׳ 2023, 02:43, מאת prb28 ***@***.***>:

**Comment by prb28** [comment]
Please try this : https://github.com/prb28/vscode-amiga-assembly/wiki/Getting-started#example-workspace
You may have some trouble with the build process so the debug info may be wrong in your binary. The sample project helps to check it.

**Comment by C64HexCoder** [comment]
I fixed the provlem by adding startup-sequence to the project and the
emulator killer util.

בתאריך יום ב׳, 11 בספט׳ 2023, 22:37, מאת prb28 ***@***.***>:
