### ISSUE TITLE
Working directory for emulator is invalid

### ISSUE THREAD

**Issue by pchalamet** [prb28/vscode-amiga-assembly#28]
Hi,
Working directory of emulator (fs-uae) is not set in the extension on launch - hence it default to the working directory of VS Code - which leads to errors on startup (both Windows and macOS). And I do not want to put fs-uae configuration into VSCode one.

I've done a patch to let user configure working directory:
````
            "buildWorkspace": true,
            "emulator": "d:\\tools\\amiga\\fs-uae.exe",
            "workingdir": "d:\\tools\\amiga\\fs-uae",
````

The patch is for review here: https://github.com/pchalamet/vscode-amiga-assembly/commit/1b22b2b1bca0b3336fb09ab3b70e1a2cfba10999 

Let me know if you are ok for a PR. If you do not agree on "workingdir", let's provide a better name for that.

Thanks.

**Comment by prb28** [comment]
Hi, thank you for this feature !
Yes, you are welcome to make a PR.
For the name what do you think about **emulatorWorkingDir** ? I think that workingdir may be confused with the workspace dir.
There is a modification to do in the package.json file, but I can do it after your request.

**Comment by pchalamet** [comment]
Good. Doing the change right now and send the PR. I will let you then bump package version number on your side. 
Thanks.

**Comment by pchalamet** [comment]
PR on the way: https://github.com/prb28/vscode-amiga-assembly/pull/29
