### ISSUE TITLE
FS-UAE/Linux: Example workspace: Unable to load UAEquit: Error code 121

### ISSUE THREAD

**Issue by Jasmin68k** [prb28/vscode-amiga-assembly#285]
Using the example workspace on a Debian Sid box, UAEquit fails with `Unable to load UAEquit: Error code 121' in the Amiga Shell.

I tested V1.8.6 and V1.8.2.

I also noticed that LD_LIBRARY_PATH seems not to be used, since I had to install libsdl2-ttf-2.0-0 to get the bundled fs-uae to run from VSCode (otherwise "[EMU] No suitable emulator binary" error). Maybe this is related to the issue.

Hope you can reproduce and fix the problem.

**Comment by prb28** [comment]
Can you please check:
- you have the executable here: yourproject/uae/dh0/c/UAEquit
- your yourproject/uae/dh0/s/startup-sequence is ok (be careful with encoding, end of line character, typo, etc.)
- you have the right permission in you linux files
The error is when you run the program directly in the amiga shell ?

**Comment by Jasmin68k** [comment]
Just ran into this https://github.com/prb28/vscode-amiga-assembly/issues/291, when I wanted to test it again, so I installed the 1.8.7 pre-release first in order to get it to work.

All I did was create the example workspace and run it and it was just UAEquit that failed after the example had been executed by the startup-sequence. Manually typing UAEquit in the shell throws the same error.

UAEquit is in c and is loaded, but quits as described. It did not get x permissions (the example binary did), when created, but adding them had no effect.

So permissions and file locations should be fine.

Note: I had to use `"noDebug": true` or run without the debugger, due to https://github.com/prb28/vscode-amiga-assembly/issues/284. Also, libsdl2-ttf-2.0-0 is still required as described (did not expect this to change  with 1.8.7 just being the VSCode bugfix).

**Comment by prb28** [comment]
Thanks, I'm preparing a new debian vm to check it.

**Comment by prb28** [comment]
With a debian 12 and the workaround to run the 1.8.7. UAEQuit worked for me.

**Comment by Jasmin68k** [comment]
@prb28 Hmm, thanks.

Should I ever find the cause of the issue, I'll report back.
