### ISSUE TITLE
vasm output suppressed during build since 1.8.4

### ISSUE THREAD

**Issue by MathsMadness** [prb28/vscode-amiga-assembly#286]
Since version 1.8.4, the output of vasm is suppressed in the tasks output window.

Please enable this again, or make it configurable via an option in tasks.json.

**Comment by prb28** [comment]
Did you look at the terminal frame ?
![image](https://github.com/prb28/vscode-amiga-assembly/assets/10462286/48a2c4b3-c57c-4b32-a499-c6678f0cc7a7)

**Comment by MathsMadness** [comment]
Yes, I am referring to the terminal frame, but to the regular output in case compilation succeeds. Until version 1.8.2, the section output is contained:

![image](https://github.com/prb28/vscode-amiga-assembly/assets/3106058/ab7497e7-25d4-4977-ad66-680f92249e95)

Since 1.8.4, the highlighted section is missing.

**Comment by prb28** [comment]
thanks, ok, maybe the stdout is not more redirected. I'll have a look.

**Comment by howprice** [comment]
I would really like this too. Think I might have mentioned this on EAB.
