### ISSUE TITLE
[VASM] Error building ....\src\demo.asm to get constants. 

### ISSUE THREAD

**Issue by prb28** [prb28/vscode-amiga-assembly#297]
With regards to the issue you mentioned in the previous post, this is an ongoing issue I have with constants. It also occurs when I open the Run and Debug > Variables > Registers > Constants node. Output:

```
[VASM] Error building c:\GitHub\howprice\Amiga3D\src\demo.asm to get constants. 

fatal error 13: could not open <demo.asm> for input
aborting...
program exited (with status: 1), but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)
```
EDIT: Please let me know if you need a repro and/or any local files for this - I seems to get it in every project.

_Originally posted by @howprice in https://github.com/prb28/vscode-amiga-assembly/issues/291#issuecomment-1925949802_

**Comment by howprice** [comment]
Thanks for adding this. Do you know if this issue is unique to me, or are you able to repro?

**Comment by prb28** [comment]
No, I had the same message during my tests, that's why I opened this issue.

**Comment by howprice** [comment]
I can reproduce this issue using the example workspace.  Please find attached a screengrab, a zip of the project (from C:\temp\) and system info (attached and in zip)

 Please could you let me know if you need any more information to help to diagnose this.

Many thanks.

[mywork.zip](https://github.com/prb28/vscode-amiga-assembly/files/14171795/mywork.zip)

[systeminfo.txt](https://github.com/prb28/vscode-amiga-assembly/files/14171790/systeminfo.txt)

![image](https://github.com/prb28/vscode-amiga-assembly/assets/13691253/451527f2-bd13-42b1-aa99-d03d3e5ed191)
