### ISSUE TITLE
tasks.json vlink includes multiple file syntax

### ISSUE THREAD

**Issue by howprice** [prb28/vscode-amiga-assembly#299]
Hi. Sorry for asking here, but I can't figure this out. How do you list multiple source files for vlink (and vasm implicitly I hope) in `tasks.json`?

I'd like to assemble a few files and link together. I'm sure this has been done many times but my search skills are letting me down. Here's what I want to do; I've highlighted the line that I need help with:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Build demo executable",
			"type": "amigaassembly",
			"vasm": {
				"enabled": true,
				"command": "${workspaceFolder}/tools/vasmm68k_mot",
				"args": [
					"-m68000",
					"-ignore-mult-inc",
					"-Fhunk",
					"-linedebug",
					"-no-opt",
					"-nowarn=2069",
					"-wfail",
					"-DDEBUG"
				]
			},
			"vlink": {
				"enabled": true,
				"command": "${config:amiga-assembly.binDir}/vlink",
				"includes": "src/demo.asm;src/clear.asm;src/line.asm",   <---  HOW TO SPECIFY MULTIPLE FILES HERE?
				"excludes": "",
				"exefilename": "../uae/HardDrives/HardDrive/demo",
				"entrypoint": "src/demo.asm",
				"args": [
					"-bamigahunk",
					"-Bstatic",
				]
			},
			"problemMatcher": [],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": false,
				"clear": true
			}
		},
```

The includes param seeems to take a single string, so I can't use an array. I've tried separating filenames with spaces, commas and semicolons. 

Thanks for any help with this.

**Comment by Real-MJoe** [comment]
Try this one :
![grafik](https://github.com/prb28/vscode-amiga-assembly/assets/40276633/82034f56-61ff-4e90-9989-e9f5bfaf69c5)

**Comment by howprice** [comment]
Thanks very much, that seems to be working as expected.

Would be great to add this to the Wiki build page.
