### ISSUE TITLE
Language Packs category is for display language extensions

### ISSUE THREAD

**Issue by gregvanl** [prb28/vscode-amiga-assembly#3]
The "Language Packs" VS Code extension category is to designate disaplay language (German, Bulgarian) extensions and not for general programming language extensions.

Please remove "Language Packs" from the categories in package.json:

```json
"categories": [
        "Formatters",
        "Programming Languages",
        "Language Packs" <--
    ],
```

**Comment by prb28** [comment]
Thank you, it will be fixed soon.

**Comment by gregvanl** [comment]
Great, Thanks!
