### ISSUE TITLE
breakpoints can not be set - File not found in Source map - compiled with vb/vbcc

### ISSUE THREAD

**Issue by cfwdman** [prb28/vscode-amiga-assembly#302]
I'm using your extension with a makefile using vc/vbcc with the kick13 option to build and launch into fs-uae.
this is the launch config and workspace is ~/Documents/FS-UAE/xdev/vscode-amiga-vbcc-example-osx_x/

{
            "type": "amiga-assembly",
            "request": "launch",
            "name": "FS-UAE Debug",
            "stopOnEntry": false,
            "trace": true,
            "program": "${workspaceFolder}/uae/dh0/hello",
            "remoteProgram": "SYS:hello",
            "emulatorType": "fs-uae",
            "emulatorArgs": [
                "--hard_drive_0=${workspaceFolder}/uae/dh0",
                "--chip_memory=1024",
                "--joystick_port_1=none",
                "--amiga_model=A1200",
                "--slow_memory=1792",
                "--remote_debugger=200",
                "--automatic_input_grab=1"
            ],
            "preLaunchTask": "Build"
}

Breakpoints can currently be set while the debugger is not started 
but are not respected when launching in this debug mode. 

While the debugger is not running the breakpoint are set to the local file and are visible as red dots.
"~/Documents/FS-UAE/xdev/vscode-amiga-vbcc-example-osx_x/hello.c"

After launching fs-uae the programm starts without the breakpoints being respected. Instead they appear as gray circles only (not red anymore) and when hovering over the breakpoint the following message appears: 
"File not found in source map: /Users/<<username>>/Documents/FS-UAE/xdev/vscode-amiga-vbcc-example-osx_x/hello.c"

**Comment by prb28** [comment]
Maybe the debug info is not added in the build. Please check your build options.
