### ISSUE TITLE
amigaassembly: ... terminal always pop up despite disabled task!

### ISSUE THREAD

**Issue by geijer** [prb28/vscode-amiga-assembly#305]
I have disabled "amigaassembly: compile current file" by this in tasks.json:

```json
...
        {
            "type": "amigaassembly",
            "vasm": {
                "enabled": false,
            },
            "label": "amigaassembly: compile current file"
        }
...
```

but everytime I save a .s file my current vscode terminal is put to back and the "amigaassembly: compile current file (...)" terminal is put to the front with the completely unnecessary message:

>  *  Executing task: amigaassembly: compile current file 
> 
> Compiling current editor file...
> VASM compilation is disabled in the configuration
> 
>  *  The terminal process failed to launch (exit code: 1). 
>  *  Terminal will be reused by tasks, press any key to close it. 

Is it possible to disable all "auto compile/build" completely?

**Comment by prb28** [comment]
You have to disable the syntax checking : https://github.com/prb28/vscode-amiga-assembly/wiki/FAQ#how-can-i-use-the-extension-without-the-syntax-checking-of-vasm

**Comment by geijer** [comment]
RTFM...
