### ISSUE TITLE
Trap instruction

### ISSUE THREAD

**Issue by NeilEricson** [prb28/vscode-amiga-assembly#315]
This bit of code will not run correctly past the trap instruction:

  move.l #mt,$80
  trap #0
 mt: .. debugging error happens here and stops with error  "Exception has occurred: 10 Bus error"

On a real Amiga if I assemble this with say Devpac (any version), or ArgAsm, heck even seka it works and executes properly. But not using vscode-amiga-assembly plugin for Visual Studio Code. Btw this is used as an easy way to eg. go to supervisor mode without the OS.

Please see https://eab.abime.net/showthread.php?t=57653 and https://wiki.amigaspirit.hu/index.php/Amiga_Machine_Language_(Chapter_8) for how it's properly used on the Amiga.

**Comment by prb28** [comment]
The trap are treated by default as exceptions in the debugger. You can uncheck the breakpoint in exception in the interface. or change the exception mask : https://github.com/prb28/vscode-amiga-assembly/wiki/Debugging-emulator#traps-68000-exception-vector-numbers---source

**Comment by NeilEricson** [comment]
Thanx for the info!

**Comment by prb28** [comment]
You're welcome !
