### ISSUE TITLE
Configuration in VC - Not clear

### ISSUE THREAD

**Issue by abelanet** [prb28/vscode-amiga-assembly#36]
Hi! I have tried and tried to follow the instructions to have VC configured, assemble code and sends it to FS-UAE but I had no success. I am finding the instructions incomplete especially for a newbie to VC like me. I am not so familiar with VC config settings. I expected that if add an extension I can somehow configure the setting by giving the path to where the rest of the files are and that's it. It looks more complicated than that. Is this something that can be sorted out and can the documentation be made more clear of how it is supposed to be configured.

Having said that I am still writing code using VC since I like the colour theme that it offers and of course it is faster to use a PC. I then save the code and read the code via AsmOne and assemble there but I would prefer if this done like with KickAssembler that you code and send the code to the C64 EMU and it runs.

Anyway keep up the good work. I think what you have achieved so far is very cool even though I am having issues.

**Comment by prb28** [comment]
Hi!
First of all, thank you, it's great to see this work used by others.
I'm sorry that the documentation is not clear, I agree with you it' sometimes incoherent and cryptic.
I will rework it next week, and if you agree, I will ask you to tell me if it's ok.

Now, I think that the most important feature of the extension (and where I spent a lot of time) is the build / run / debug with FS-UAE. With AsmOne I was frustrated to not have a debugger with a working copper list ! And this reminded me why, in the late 80s, I ended using AMOS...

So the easiest way to make it work is to download the vscode-amiga-wks-example [release file](https://github.com/prb28/vscode-amiga-wks-example/releases/download/0.10/vscode-amiga-wks-example.zip), unzip it and open the workspace file with vscode according to your os.
You may follow this [animated gif](https://raw.githubusercontent.com/prb28/vscode-amiga-wks-example/master/images/debug.gif).

Hope this helps !
If not, can you please tell me which os you use ?

**Comment by abelanet** [comment]
Hi!

Thanks for your reply and apologies for the late reply actually. So the good news is, it worked as you stated. The issue was the Animated Gifs to understand them. They are fast and you can't stop them. I recorded a video of them while playing and then observed what you did and hey in a few minutes I was up and running.

There I suggest that you replace the GIFs since I am sure there are others with the same issues. Replace these with videos.

Thanks once again and keep up the good work. Loving the tool now. I can cross assemble easily from my Windows Machine.

Coding is fun :)

**Comment by prb28** [comment]
Great !
I will try some video... but I'm really not good at it.

**Comment by nattfalk** [comment]
@abelanet, If running from Chrome you could always download the extension GIF Scrubber, https://chrome.google.com/webstore/detail/gif-scrubber/gbdacbnhlfdlllckelpdkgeklfjfgcmp, which enables pausing and scrubbing back/forth in GIFs.

**Comment by denissopovic** [comment]
Hello! A newbie here too that tried following the configuration instructions. I got so far that it compiles and makes an executable. But when I try to run the "OSX Run" to get the FS-UAE up I get the following error message in the output:

`yld: Library not loaded: @executable_path/../Frameworks/libgthread-2.0.0.dylib
  Referenced from: /Users/denis.sopovic/amiga-asm/vscode-amiga-wks-example-master/bin/osx/fs-uae
  Reason: image not found
`
Otherwise thanks for a solution that seems to be a really good option to get back into some Amiga democoding again =D

**Comment by prb28** [comment]
Hi,
On Osx the lib (dylib) path resolution is ... special ...
I did some custom fixes in the build but maybe the last one does not have it right.
Could you, please, try this one: https://github.com/prb28/vscode-amiga-wks-example/releases/download/0.11-1/vscode-amiga-wks-example.zip ?

If it doesn't work could you tell me which version of osx you use ?
And if the .dylib are in the directory of fs-uae binary.

**Comment by denissopovic** [comment]
Thanks @prb28 for fast reply. Not sure how I missed to add the dylib inside the /bin/osx folder. It was not there. But I downloaded the link you provided me and replaced the folder. 

And now I get the FSUAE up and running =D.. Although I just get a black screen from the gencop-source I compiled. But at least its a step forward and I'll dive into it as soon as I have more time.

**Comment by prb28** [comment]
The black screen is normal if you are stopped in the debugger before the copper list is set. For the gencop.s, it means if you have a breakpoint before line 124 or 133.

**Comment by prb28** [comment]
The version 1.0 is better suited for beginners.
