### ISSUE TITLE
Display used/free registers in selected codeblock

### ISSUE THREAD

**Issue by nattfalk** [prb28/vscode-amiga-assembly#48]
Would be nice to be able to select a codeblock and get a display in the statusbar which register are used/not used. For example 
"Registers used: d0-d1/d5/a1-a3/a7 - Free: d2-d4/d6-d7/a0/a4-a6" or
"Registers used: d0 d1 d5 a1 a2 a3 a7 - Free: d2 d3 d4 d6 d7 a0 a4 a5 a6".

**Comment by prb28** [comment]
I agree with you, it will be added in the next release.
