### ISSUE TITLE
Error on start debugging with kickstart1.3

### ISSUE THREAD

**Issue by ghost** [prb28/vscode-amiga-assembly#49]
I've change the lunch.json file, so that I could use the original amiga rom kickstart1.3. To do that I've added this option: "--kickstart_file=${workspaceFolder}\\fs-uae\\kick13.rom" to the debugging part of the json file.

When I start debugging an alert messagebox pops up with the content: Error: ECONNRESET

**Comment by prb28** [comment]
Thanks, 
On osx, fs-uae crashes, must be the same bug.

**Comment by dhjneuwonf** [comment]
Just landed here after searching for the cause of this issue. The 0.11-2 workspace works for me! I can now launch a remote debugging session in 1.3. Thank you for your excellent work in this project overall.

**Comment by prb28** [comment]
@dhjneuwonf thanks for this feedback !
