### ISSUE TITLE
Is copper debugging already functional ? 

### ISSUE THREAD

**Issue by cvalcke** [prb28/vscode-amiga-assembly#51]
A simple call at WaiTOF() generate a Segfault and I would just like to know if copper debugging should be implemented ?

![selection_011](https://user-images.githubusercontent.com/354495/52013295-f565b800-24dc-11e9-9425-fd9f1ef5ff9b.png)

![selection_012](https://user-images.githubusercontent.com/354495/52013302-f991d580-24dc-11e9-8d3d-00869b2574d8.png)

**Comment by prb28** [comment]
copper debugging is implemented in version 0.14 (will be release today)
