### ISSUE TITLE
Feature:  Sinus data generator

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#57]
iIt would be nice if the tool could generate sine data like ASM-ONE.

**Comment by prb28** [comment]
I didn't know this option integrated in asm-one (never really used it), do you have some docs ? 
Do you have some other simple functions that would be interesting in mind ?

**Comment by Real-MJoe** [comment]
look like this:
![fs-uae-crop-1903301052-01](https://user-images.githubusercontent.com/40276633/55274634-72918b80-52da-11e9-95e0-1f172746fc10.png)

result is:
![fs-uae-crop-1903301052-02](https://user-images.githubusercontent.com/40276633/55274640-82a96b00-52da-11e9-8495-fb2c4f8b8aab.png)

**Comment by prb28** [comment]
thanks
