### ISSUE TITLE
Missing vasm Link Error

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#59]
If there is an include to another file in the source code, the errors of vasm are not displayed.
A message "Build aborted: there are compile errors" is displayed, but the error message itself is missing.

If I compile the whole thing manually, the vasm spits out the errors including the line number.

**Comment by prb28** [comment]
Thanks, I did reproduce it.
As a workaround you may use the "output" tab (menu: view/Output), if you select "Amiga Assemby" in the combo you will see all the errors from vasm / vlink.
