### ISSUE TITLE
Feature: Define from PreBuild and PostBuild

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#60]
It would be nice if there was a way to run a script before or after the creation process. For example to delete or move files.

**Comment by prb28** [comment]
It sounds like a real build system is needed: makefile / gradle / cmake / etc...
A definition of a prebuild / postbuild vscode task may be the way.
But I don't want to go too far, build systems are better for that.
Integrating [gradle-native](https://github.com/gradle/gradle-native) as build system may be a better choise, but harder and less userfriendly.

**Comment by prb28** [comment]
This already can be done with vscode tasks.
Create a .vscode/tasks.json with:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "PreBuildTask",
            "command": "echo",
            "args": [
                "start"
            ]
        },
        {
            "label": "Amiga Build",
            "type": "process",
            "command": "${command:amiga-assembly.build-vasm-workspace}",
            "dependsOn": [
                "PreBuildTask"
            ]
        },
        {
            "label": "Complete Build (with postbuild)",
            "command": "echo",
            "args": [
                "end"
            ],
            "dependsOn": [
                "Amiga Build"
            ]
        }
    ]
}
```
For further documentation: [vscode tasks](https://code.visualstudio.com/Docs/editor/tasks).
