### ISSUE TITLE
Version 0.15 does not show up in VSCode

### ISSUE THREAD

**Issue by mithrendal** [prb28/vscode-amiga-assembly#61]
how long does it need, that the new version 0.15 shows up ? 

Background:  I had an issue yesterday in getting the adf creation working. I read the docs in the wiki but they were already for 0.15. I bet the new ADF settings are too advanced to be compatible  with my installed 0.14 ... ;-)

PS:
Thank you very much for this great piece of software ! It is so much fun, it really makes retro-coding  looking modern again ;-) ...

**Comment by prb28** [comment]
First: thanks !

In my last minutes testing for the 0.15 I found a bug in the new features. So it’s fixed, but not released (in the marketplace).

I hope I’ll have the time this evening to release it. If not it will be done in the weekend.

**Comment by prb28** [comment]
Done now !

**Comment by mithrendal** [comment]
I love it.

**Comment by mithrendal** [comment]
just had my first debug session. Cool. ADF also builds now. Vachement cool c'est ca.
