### ISSUE TITLE
IntelliSense for commodore libraries

### ISSUE THREAD

**Issue by mithrendal** [prb28/vscode-amiga-assembly#63]
Hi prb28,

I can't really express in words how great this visual studio code extension already is. I really want to express my heartful thanks and admiration for your work.

Now I will come to the thing which might be a cool enhancement. I have a .i file with all the offsets  
```

* Important Exec Library Offsets
AbortIO            equ -480
AddHead            equ -240
AddIntServer       equ -168
AddTail            equ -246
Alert              equ -108
AllocMem           equ -198
...
```

and this file I do include in my .s files. I had to install the extension "All Autocomplete" to get the constants of the .i file  recognized  when I edit the .s file. This leads my to a further question:

How can I extend IntelliSense in VSCode on library calls. When the mouse is over a lets say

` jsr AllocMem(a6)
`

I would like to see a hint like this

```
NAME
    AllocMem -- allocate memory given certain requirements

SYNOPSIS
    memoryBlock = AllocMem(byteSize, attributes)
    D0                     D0        D1
...

``` 

Is that maybe easy possible to add to Amiga-Assembly  ?

with best regards

**Comment by prb28** [comment]
First (and always): thanks.

This is an interesting feature.
The big part of the work is to create a bunch of markdown files for each function like [DFF090_DIWSTOP](https://github.com/prb28/vscode-amiga-assembly/blob/master/docs/hardware/DFF090_DIWSTOP.md).
For the registers, I did a little python script to transform the web pages in markdown...
This needs some work to create and review, for the rest it is easy to integrate.

**Comment by mithrendal** [comment]
As a startinb point I would suggest [this source of information](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node000E.html)

Maybe I can help you out? I could use wget and transform them into  .md files?

I would suggest only to use the most important libs first?
Maybe
exec
graphics
dos
intuition?

**Comment by prb28** [comment]
Yes, that would be great if you get the docs in .md format!

I agree with the source (I've used this when I've modified the fs-uae boot code).
The base libraries you have submitted seem to be the most important (but I'm too new to that to know).

There is maybe a difficulty with the kickstart version / compatibility with the api. I don't know if the api had much refactoring from first version to the last one.

**Comment by mithrendal** [comment]
Parfait !
Je vais essaye ca. Mais je vais besoin de quelqe jour avec ca je crois. On le page de cette source il y a écrit  "These files are made available here free of charge ". C'est pour ca je crois il n'est pas vraiment necessaire pour demander, si on est permis pour utilisier le content des cettes fichers.

Pour la question de la compatibilite. Je pas vu des autres source en ligne. Et pour ca nous avons pas du choix. Mais je personalment crois que commodore fait le nouveau version des library sans "breaking" le compatibilite avec le vieux "executeables". Pour le debut est pour la raison de compatibilite en les deux directions,  je ne vais pas inclure les entrees >AmigaDOS1.3 et surtout je vais choix seulment les plus importantes entrees de AmigaDOS v1.3.

Je espere que tu peux comprend mon francaise scolaire ....

**Comment by prb28** [comment]
Ton français est excellent !
Je ne ferais certainement pas mieux avec mon anglais technique.

Il n’y a pas d’urgence à faire les fichiers.

En effet, je crois que cette documentation est accessible à tous. Pour l’api si les fonctions entre les versions ne sont pas les mêmes on peut toutes les conserver, cela sert surtout d’aide mémoire.

I can still write in English, even if it’s like a alien ;-)

**Comment by mithrendal** [comment]
Yes lets mix languages. In the end I think francaise is more elegant. But english is still more easy for me. Deutsch ist noch einfacher. 

wget was not so good, parce que seulment telecharger les fichiers,  n'est pas suffit. Il faut les transformer un peux.  I ended up with a mini python program. J'ai tous les fichiers de exec. Looks pretty promising. Now I have still to translate the links into the md markup style...
Je vais continuer demains. 
When I am done I can use the python script for the rest of the libraries...

**Comment by prb28** [comment]
ich habe deutsch gelernt, aber ich bin very bad at it. J’ai fini avec 0,2/20 de moyenne...

Yep python is the way... (there is perl  too :-))))

**Comment by mithrendal** [comment]
das macht nichts !!  Vive l'amitie franco allemande. 😃

Schau mal hier. I have got the exec libarie ready. Can you use it ?
[exec.zip](https://github.com/prb28/vscode-amiga-assembly/files/3113863/exec.zip)

If Amiga-Assembly is happy with it I will create the other ones with the python script ...
If not let me know what's missing...

**Comment by prb28** [comment]
Excellent! I’ll try tomorrow evening.

**Comment by endo64** [comment]
@mithrendal Unfortunately the file you've shared is not exactly formatted as a proper MD file.
There are small changes need to be done one the file, see the below picture how it look previewing as MD:

![image](https://user-images.githubusercontent.com/840604/56729587-4f81bc80-675e-11e9-9f85-2266888e56ce.png)

We might need to write a simple converter/fixer to format correctly. For example, put one additional newline after these items:

NAME
SYNOPSIS
FUNCTION
WARNING
INPUTS
RESULTS
SEE ALSO

Shouldn't be difficult anyway.

**Comment by mithrendal** [comment]
@endo64 Yes I see. This is easy. I will do as you suggest and change the python generator script this evening.

**Comment by mithrendal** [comment]
new Version with the correctings as @endo64 suggested plus I took the parentheses out of the markup URLs. 
Before it generated 
`[AllocMem()](/exec:AllocMem()) 
`
now in new version it generates
`[AllocMem()](/exec:AllocMem) 
`



[exec_20190425.zip](https://github.com/prb28/vscode-amiga-assembly/files/3118237/exec_20190425.zip)

**Comment by mithrendal** [comment]
Here is the same graphics library in the same format...

[graphics_20190425.zip](https://github.com/prb28/vscode-amiga-assembly/files/3118541/graphics_20190425.zip)

**Comment by prb28** [comment]
Looks good, but I have some weird color in the hover
![hover](https://user-images.githubusercontent.com/10462286/56762663-a6a88100-67a0-11e9-9585-a315862c68d3.png)
I'm looking for the reason...

**Comment by mithrendal** [comment]
I see, it interpretes the asterix symbol of the C-style pointer as markup information. I must somehow quote the asterix I think...

**Comment by prb28** [comment]
It's using the same colors as the asm source file: 'library' is a variable, A1 is a register and * is a comment.
This is because the spaces before the text is interpreted as a 'code bloc', so vscode thinks it must be in asm.

**Comment by mithrendal** [comment]
Ah I see... and not is blue ? strange

**Comment by prb28** [comment]
![Capture d’écran 2019-04-25 à 21 53 51](https://user-images.githubusercontent.com/10462286/56764328-bd50d700-67a4-11e9-86cc-e2221871814b.png)

`
**NAME**

OldOpenLibrary -- obsolete [OpenLibrary](/exec:OpenLibrary)

**SYNOPSIS**
```
library = OldOpenLibrary(libName)
D0                       A1
```
struct [Library](/exec:Library) *OldOpenLibrary(APTR);

**FUNCTION**

The 1.0 release of the Amiga system had an incorrect version of
[OpenLibrary](/exec:OpenLibrary) that did not check the version number during the
library open.  This obsolete function is provided so that object
code compiled using a 1.0 system will still run.

This exactly the same as &#034;OpenLibrary(libName,0L);&#034;

**INPUTS**

libName - the name of the library to open

**RESULTS**

library - a library pointer for a successful open, else zero

**SEE ALSO**

[CloseLibrary](/exec:CloseLibrary)
`

I'm looking how to make the links work, don't know if it is possible in vscode.

**Comment by prb28** [comment]
```

**NAME**

OldOpenLibrary -- obsolete [OpenLibrary](/exec:OpenLibrary)

**SYNOPSIS**
\`\`\` (remove the \)
library = OldOpenLibrary(libName)
D0                       A1
struct [Library](/exec:Library) *OldOpenLibrary(APTR);
\`\`\` (remove the \)

**FUNCTION**

The 1.0 release of the Amiga system had an incorrect version of
[OpenLibrary](/exec:OpenLibrary) that did not check the version number during the
library open.  This obsolete function is provided so that object
code compiled using a 1.0 system will still run.

This exactly the same as &#034;OpenLibrary(libName,0L);&#034;

**INPUTS**

libName - the name of the library to open

**RESULTS**

library - a library pointer for a successful open, else zero

**SEE ALSO**

[CloseLibrary](/exec:CloseLibrary)

```

**Comment by mithrendal** [comment]
Looks good. So what do I have to change ?

only the `**NAME**` and so on ? 

what is the 
` \`\`\` (remove the \)`  thing ?

**Comment by mithrendal** [comment]
I accidently closed it.  😎 Git hub UI should really not combine "Close and comment" in one button... Haha. Github are you hear me ?

**Comment by prb28** [comment]
Yes there is:
- the bold with ***
- the starting spaces are removed
- the special line: ``` means 'bloc of code' (instead of starting spaces)
[OldOpenLibrary.md.zip](https://github.com/prb28/vscode-amiga-assembly/files/3118671/OldOpenLibrary.md.zip)

**Comment by mithrendal** [comment]
can I put the complete synopsis into bloc of code ?
That means from SYNOPSIS until the beginning of FUNCTION?

**Comment by prb28** [comment]
Yes, it's the only way I found to have indented text... but I can be wrong.

**Comment by prb28** [comment]
oh, no the link won't be interpreted

**Comment by mithrendal** [comment]
[execV3.zip](https://github.com/prb28/vscode-amiga-assembly/files/3118771/execV3.zip)

**Comment by prb28** [comment]
Better! close to the end!
but the groups of 4 leading spaces must be removed and the bloc of code cannot contain a link.
here is a modified file:
[MakeLibrary.md.zip](https://github.com/prb28/vscode-amiga-assembly/files/3118847/MakeLibrary.md.zip)
For the links, `[AllocMem()](/exec/AllocMem.md)` ... I'm still searching what should be their format. I think I'll have to refactor them on the fly by adding the plugin path.

**Comment by prb28** [comment]
I've pushed some modifications, so, if you want, you can try yourself.
I still haven't found a good way to navigate in the documentation.

**Comment by mithrendal** [comment]
Question: when there are more than 4 leading spaces in a line. 
For example there are 6, 

should the python generator script remove the 4 spaces only and leave the 2 spaces in the line 
or 
should it remove all 6 leading spaces from that line ?

**Comment by prb28** [comment]
If there is leading spaces it will not be considered as the same paragraph.
So yes all 6 must be removed.

**Comment by mithrendal** [comment]
Easy. Will repair that this evening. Together with the links in the code block. 

What about leading spaces inside the code block should I remove them too? In your examples you did not.

**Comment by prb28** [comment]
In the code bloc the spaces look good.
But don’t process everything for now, I have to resolve the problem of the documentation links resolution to navigate between the docs.

**Comment by mithrendal** [comment]
I only did exec.library again, slowly moving to perfection ... 😅

[execV4.zip](https://github.com/prb28/vscode-amiga-assembly/files/3122649/execV4.zip)

if you are interested in the current state of the script ...
[getthedocs.py.zip](https://github.com/prb28/vscode-amiga-assembly/files/3122658/getthedocs.py.zip)

Tell me what you need next 😃...

**Comment by prb28** [comment]
This version seems pretty good.
I've figured how to handle the links in the documentation, so I've a little request.
Could you change the links with a relative path to the other documentation page.
As an example with two files in the same directory:
```
[OpenLibrary](/exec:OpenLibrary) 
```
will become:
```
[OpenLibrary](OpenLibrary) 
```
If they are in different directories:
```
[OpenLibrary](../exec/OpenLibrary) 
```
If it's easier the second form with the path `../exec/OpenLibrary` can be always used.

**Comment by mithrendal** [comment]
try this...
[execV5.zip](https://github.com/prb28/vscode-amiga-assembly/files/3124176/execV5.zip)

do you have an example where the doc jumps into different directories ?

**Comment by prb28** [comment]
Thanks, this seems good! Here is the extension with docs so you can see the result of your work:
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3124266/amiga-assembly-0.17.0.vsix.zip)

I do not have an example of a link in a different directory, so it may not exist!
(maybe you'll found some...)

**Comment by mithrendal** [comment]
Wow, that is amazing cool ! It works. Je suis super content! 😊

There are still sometimes some lonely links to nowhere. Basically these are links not included in the main lib entries index. For example a link to a certain struct ...
Of course our python program can be modified to also follow these type of links and download the referenced doc next to the referencing md file. As it looks I will do have a new tasks. 

But this version is also really cool for me I think. 😉

**Comment by prb28** [comment]
I think it's cool feature too.
Well now, you're the main user, so choose what you think the goal for a first release is.
This means what will meet your needs (and maybe @endo64 ), and I will do the release when ready.

**Comment by mithrendal** [comment]
I think to teach the python script to collect the additional docs is also not very difficult. The are several approaches to it fully recursive or not recursive, etc...
At the moment I think, I will just refactor the script, so that it will additionally collect the links of a single doc file which are not already in the main "lib entries link list"  and add process them afterwards in the same manner as each of the main lib entries. This way it should automatically take care of cross library references.

**Comment by mithrendal** [comment]
harder than I thought. I have it now that it collects the additional docs. But a remaining thing is that these docs are referenced to by multipe other docs under different names. As for now I only worked with visible names only and removed the technical filenames urls (the thing in href=".."). But now I have to rewrite the whole program in order that it uses these technical url-names when linking to the additional docs...

To get it solid I will need some days more than I thought.😀

**Comment by prb28** [comment]
Looks like a highway to hell ;-)

**Comment by mithrendal** [comment]
It works now. But is no python script anymore. 😅 I will call it from now on no more only script. The script said to me I should call it program from now on. 😂

The test run was fine. I think I have got it now. But I will do some more deeper checks on more docs tomorrow.

**Comment by mithrendal** [comment]
exec library docs,  now updated with all links to structs and other non lib entry description files, which are also included now. Easy to see when you look at the docnames. Additional doc files have numbers as name. For example "0099.md". Can you exclude these extra files from VSCode code completion lookup ?

Now there should be no link anymore which leads to nowhere. At least I hope so. 😅

[execV6.zip](https://github.com/prb28/vscode-amiga-assembly/files/3128849/execV6.zip)

**Comment by mithrendal** [comment]
Do you think it could already be prime time for the graphics library ? 

This one uses a lot of additional structures, like viewport, rasport, colormap, bitmap ...
It is also huge ...

[graphicsV1.zip](https://github.com/prb28/vscode-amiga-assembly/files/3128961/graphicsV1.zip)

A good test candidate.

**Comment by mithrendal** [comment]
I could also prefix the second level doc files with another char, for example with an underscore if it is easier or Amiga Assembly ...

for example  __0099.md_

**Comment by prb28** [comment]
vscode does not seem to accepts the number in the links of hovers (popups).
Do you have a way to rename them only with letters ?
0094.md -> _OOID.md (I've added _ as you thought is the best way to filter them)
These files are mainly C headers, could you add a code bloc link this ?
```
```c
\``` (>remove '\')
```

I found the vscode accepts some markdown from github.
What do you think about a synopsis bloc with
```
```c
    AbortIO(iORequest)
            A1
    VOID AbortIO(struct IORequest *);
\``` (>remove '\')
Links: [IORequest](CODE_AAEF)
```

Result: 
```c
    AbortIO(iORequest)
            A1
    VOID AbortIO(struct IORequest *);
```
Links: [IORequest](CODE_AAEF)

Do you think it could be done?

I don't know if the 3rd inclusion level is necessary do you have an example ?

Some sublinks are in different libraries: 014A.md -> [dos.library/CreateProc](028E) it's a function from dos library. Should be `../dos/CreateProc`. (If it's not easy it can stay like that).

**Comment by mithrendal** [comment]
Point 1: to decode the number into alphabetic filenames + prefix them with underscore is super easy.
Point 2: additional files should start with a ````c  and end with ```. The c stands for code ? That is easy too.
Point 3: easy to do when only one link in a code block. But what should the generator do if there are two links in a codeblock ? 
Answer: I think 3rd level docs are only detected by the generator if the 2nd level doc is not a header file but a link to a different library.
Point 4: also on my todo list now. ;-)  Especially "Point 2" is applicable on c header files only not on external library entries...  So I will have to differentiate the type of the 2nd level doc anyway...

ce soir je vais voir dans cette matiere... ;-)

**Comment by prb28** [comment]
Point 2: the c stands for language C, that why the colors are better suited. 
Point 3: With two links I think a list of links without separator could be good.

Bon courage !

**Comment by mithrendal** [comment]
Point1: accomplished. 😎

**Comment by prb28** [comment]
Es ist fast fertig !
I saw two small points (keep on counting ;-)):
Point5: There is a ````c bloc at the beginning of the files that is not useful
Point6: It's missing a newline before the ***Function*** title
Here is the resulting extension (exec is in v7 graphics is old)
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3134065/amiga-assembly-0.17.0.vsix.zip)

**Comment by mithrendal** [comment]
Point5: accompli
Point6: accompli

[execV8.zip](https://github.com/prb28/vscode-amiga-assembly/files/3134819/execV8.zip)


But I will relook the Point4, I am not sure if it is done right... will check that now

**Comment by mithrendal** [comment]
Point4: accompli 🤓

[execV9.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135023/execV9.zip)

**Comment by prb28** [comment]
Wunderbar!
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135163/amiga-assembly-0.17.0.vsix.zip)
I think it's great like that!

**Comment by mithrendal** [comment]
references to other libs should work now correctly. I did the dos lib for testing.


exec/AddTask-> amiga.lib/CreateTask->dos.library/CreateProc() 
is translated to
exec/AddTask.md->_OQTA.md->../dos/CreateProc

[dosV9.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135144/dosV9.zip)
[graphicsV9.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135145/graphicsV9.zip)

**Comment by prb28** [comment]
Once again the links in the popup (hover) acts weird, it does not seems to accept the '.'.
In exec/AddTask:
That's ok: [amigalib/CreateTask](_OQTA)
This one does not work: [amiga.lib/NewList](_OQVQ)
(The two work when the documentation is opened in the markdown preview)
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135201/amiga-assembly-0.17.0.vsix.zip)

**Comment by mithrendal** [comment]
Hmm, I can not test the link. 

At exec/AddTask.md:
NewList link in the middle of the text works but when I want to move the mouse icon over the amiga.lib/NewList link at the bottom of the popup then it popup closes automatically. 
Do you see this too ? Maybe we should add multiple newlines at the end of the *.md files ?

**Comment by mithrendal** [comment]
Tu as deja cette fichier ? I work with it ... 🤗
[liboffsets.i.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135472/liboffsets.i.zip)

**Comment by prb28** [comment]
> The amiga.lib/NewList link is the last thing in the md file. Can you add a newline after the amiga.lib/NewList link and test if it works ? If so we just append an extra newline to each md file.
I've edited the *amigalib/CreateTask*, before it was *amiga.lib/CreateTask*, that's why it works.
There is no problem with the fact that it's the last line, there is already an extra line at the end of the file.
Replacing *amiga.lib/NewList* by *amiga_lib/NewList* works too.

If you want to try it easily, I think you can change the plugin directory contents in you vscode installation. (I've never tried)

Thanks for the liboffsets.i it's pretty straightforward, actually I use a bunch of standard '.i' files from commodore with macros. I try to stick with something that other people will get from internet.
I'm transforming my example workspace to have the name of functions to demonstrate the feature.

**Comment by mithrendal** [comment]
Now I understand. 🙃 V10 replaces the . char from the text of the link with _ 

[execV10.zip](https://github.com/prb28/vscode-amiga-assembly/files/3135938/execV10.zip)

**Comment by prb28** [comment]
Great, the '.' replace by '_' works!
But, I'm sorry! I did you work for nothing, it was my fault, I did a bad parsing on the links with '.'. It works now with the two syntaxes.

I've a question in exec/AddTask there is the link: `[dos/CreateProc](_ORXE)`, shouldn't it be `[dos/CreateProc](../dos/CreateProc)`?

**Comment by mithrendal** [comment]
d'accord moi je removed the replacement of the . and went back to v9 😄. Ici je te donner deux biere 🍺🍺 pour ton traveaux fantastic.

Why is dos/CreatePro outputted as `[dos/CreateProc](_ORXE)` and not `[dos/CreateProc](../dos/CreateProc)`?

The short answer is: That is not assumed as a call to a different ib, because it has not the syntax dos.library/CreateProc().

The detailed answer is:
The python generator analyses the link and has currently three possible decisions 
1. it is a link to the current lib 
     -> create a link to the name
2. it is a link to an function entry in a different lib 
     ->create a relative link ../
3. it is neither 1 nor 2 and must be a 2nd level document 
     -> open/follow the link, make an .md  file with the technical id  

here is the corresponding code fragment of the python **program** 😄
```
	#if the link points to an lib entry then use its name as url
	if(mapLibentriesURLsToName.has_key(lurl_orig)):
		lurl=mapLibentriesURLsToName[lurl_orig]
	#if it is a link to an external lib
	elif re.match(".*?[.]library/.*", lname_without_brackets):
		lurl= re.sub("(.*?)[.]library/(.*)",r"../\1/\2",lname_without_brackets)
	#otherwise use the technical document id
	else:
		lurl=encodelink(lurl_orig)

```

When we want to get rid of the somewhat redundant created md files (_ORXE.md), then we have as a first action in the python program to read all libentries of all different libs that we plan to generate. Then the python program can **optimise its decision taking**, because it has not to guess if dos/CreateProc() is really an existing entry in ../dos/CreateProc by syntax. It will know it because it collected all URLs the lib entry points beforehand and therefore can then make the decision by looking up the URL instead of the link text. 

Currently the python program only processes one library at the time.

**Comment by prb28** [comment]
Ok I understand and agree It can be tricky for only some extra files.
So we can keep it like that.
One last question, are some files missing? _OSOV.md, _ORDT.md, _ORXD.md  
If it's a problem of the conversion 1234.md->OABC.md, you can remove this conversion too, this was needed because of my parsing bug.
 
[amiga-assembly-0.17.0.vsix.zip with V9 docs](https://github.com/prb28/vscode-amiga-assembly/files/3139388/amiga-assembly-0.17.0.vsix.zip)

**Comment by mithrendal** [comment]
I have thought about it and came to the conclusion that the current way of only doing one lib at a time without knowing the technical link id of the others leads to a problem:  Missing files on the 3rd doc level -> _OSOV.md 😱

You yourself also discovered the same problem _OSOV is missing !!!Who the f*** is OSOV ? 😉 

Why are there missing files ? Because we don't follow the links to the 3rd level.  The files you mentioned are all 3rd level docs.

But instead of generating copies of the 3rd level docs (which would solve the problem for 3rd level only (maybe there are 4th level still ??)), we better do the concept of **optimized decision making** which I described in the post above. With the relative links we do not need these docs at all, which are basically copies of already existing doc files.

Who is OSOV ?
_OSOV.md   is equal with  /dos/UnLoadSeg.md    

En effet I am just reworking the python program. 😌

**Comment by mithrendal** [comment]
+new optimised link decision
+numbers instead of alphas in 2nd level docs

[execV11.zip](https://github.com/prb28/vscode-amiga-assembly/files/3139954/execV11.zip)

**Comment by prb28** [comment]
That's great! Everything seems to ok.
Now it's my time to work ;-).
I'm thinking to add some code completion and maybe a summary to view the doc contents.
Do you see other things to add ?
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3140758/amiga-assembly-0.17.0.vsix.zip)

**Comment by mithrendal** [comment]
I think it is really great !!! 

In _009C.md I still see some html entities for example` &#034; and &#060;` which are not rendered by Visual Studio Code. 

`&#034` is a  &#034; and `&#060;` is a &#060; 

I bet it does not render because it is in the code block right ? 
Should I replace html entities to it corresponing ascii when inside the codeblocks for you ? 
Or can you teach VisualStudioCode to render it even if it is in code bloc ?

**Comment by prb28** [comment]
Yes it's because of the code block.
To do it in my side, I'll have to implement a custom markdown renderer, and it may be tricky.
If you can, the best is to clean it up in the code blocks. Apparently in the markdown (outside the codeblocs) they are replaced.

**Comment by mithrendal** [comment]
Yes it was a better decision to do it on my side. Now I think we can let the other libs have their prime time 😄 what do you think ? I have generated now the most important libs. Then maybe later if everything is ok we can also do the other less important ones.


[V12_diskfont.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144117/V12_diskfont.zip)
[V12_dos.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144118/V12_dos.zip)
[V12_exec.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144119/V12_exec.zip)
[V12_graphics.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144120/V12_graphics.zip)
[V12_intuition.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144121/V12_intuition.zip)

**Comment by prb28** [comment]
Thanks! Here is the new version, with some completion (work in progress...).
[amiga-assembly-0.17.0.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3144228/amiga-assembly-0.17.0.vsix.zip)

**Comment by mithrendal** [comment]
Looks good 👌

**Comment by prb28** [comment]
I've just watch the [interview of Mike Battilana](https://www.youtube.com/watch?v=fHjXwH53_Nk). As I understand the commodore documentation is still copyrighted (as the logo, name, etc.), I will send him a email, to get his agreement on this use.

**Comment by mithrendal** [comment]
Ah cool. Did you sent the question on his website contact formular? I think it is this https://www.amigaforever.com/contact/

Maybe he is even on EAB? Elowar , the one who hosts the source from which we got the docs is at EAB. His name there is also Elowar. Maybe it is also Mike Battilana ???

**Comment by prb28** [comment]
I sent it to mike at amiga dot com seems to be his direct address.

**Comment by mithrendal** [comment]
Cool. 😏 mike at commodore dot com is maybe also working ...

**Comment by mithrendal** [comment]
Hi @prb28 
something completely offtopic: 

do you you know the **vAmiga** project? Maybe interesting and funny for you to look at ? ;-)
https://github.com/dirkwhoffmann/vAmiga/issues/9

**Comment by prb28** [comment]
Thanks, yes it's really interesting! (I'll keep a eye on it!) 
Daniel Collin is working on a new emulator too:  https://github.com/theblacklotus/magia.

**Comment by C64HexCoder** [comment]
How do i install the library extension in Amiga Assembler visual studio?

**Comment by prb28** [comment]
@C64HexCoder You'll get this feature with the extension. Although all the libraries are not documented.
