### ISSUE TITLE
Debug C source files

### ISSUE THREAD

**Issue by prb28** [prb28/vscode-amiga-assembly#66]
Stepping in source files.
Variables evaluation (if possible).

**Comment by prb28** [comment]
The step is made with asm instructions so it takes several times (F10 key pressed) to pass from one line to another in the C code.
I don't know if it is better to stay like that and show the asm in another window (better insight) or to make a real C step to the next C instruction (may be tricky to implement).
Someone has an opinion ?

**Comment by mithrendal** [comment]
I think it is ok as it is, I mean the step granularity of asm instructions ... But inspection of variables would be so cool if you could that figure out ? Maybe not so easy ? As you don't know which variable is stored in which register ?

BTW:
My crash of the c/c++ extension from microsoft is not your new b2 workspaces fault. I just created a new empty workspace with just one c file in it and it crashes. To repair it I will have to remove visual studio code and reinstall it, I think... ce serai une devoir pour demain ...

**Comment by prb28** [comment]
Yes I think the inner view of the asm, may be a good thing -> the current asm line must appear somewhere to be understandable.
I'll ask on [eab](http://eab.abime.net/index.php), if someone knows how to evaluate a variable.
Bon courage pour tes devoirs de demain ;-).

**Comment by prb28** [comment]
The discussion on eab: http://eab.abime.net/showthread.php?t=97398

**Comment by prb28** [comment]
Variable evaluation moved to issue #70
