### ISSUE TITLE
Presentation of the value set to a register $102 (BPLCON1)  is wrong.

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#68]
Hello,

the presentation of the register $dff102 ist wrong.

wrong:
![grafik](https://user-images.githubusercontent.com/40276633/58368187-d0f97580-7ee9-11e9-8e18-f24ac9a06579.png)

right;
![grafik](https://user-images.githubusercontent.com/40276633/58368221-46fddc80-7eea-11e9-8d1d-3462841ff473.png)

Book Amiga intern:
![grafik](https://user-images.githubusercontent.com/40276633/58368225-50874480-7eea-11e9-8a13-6382f960cd29.png)

regards Joe

**Comment by prb28** [comment]
Thanks for the report, I'll fix that in next release.

**Comment by prb28** [comment]
My source is this page :
http://amiga-dev.wikidot.com/hardware:bplcon1
It seems to be some AGA registers:
http://eab.abime.net/showthread.php?t=79840&highlight=BPLCON1+PF2H7&page=2

**Comment by prb28** [comment]
I've found a lot of documentation tables wrong. I've fixed these.
I have added a comment telling these descriptions are not in the reference manual.
