### ISSUE TITLE
Contextual documentation: not all mnemonics are recognized

### ISSUE THREAD

**Issue by tehKaiN** [prb28/vscode-amiga-assembly#74]
Some mnemonics doesn't trigger tooltips:

- bhs - branch if higher or same
- dbhs - decrement and branch if higher or same

Also, perhaps it should go into separate issue, as an asm noob I think it would be very helpful to have a bit of actual description for given mnemonic - I'm always confused with compare order. ;)

**Comment by Real-MJoe** [comment]
"blo" is also still missing.

**Comment by tehKaiN** [comment]
Okay, I've got one more mnemonic for you ;)

- shs - set if higher of same

Also, I see that there's a list of instructions here https://github.com/stevenjs/M68k-Assembly/blob/master/M68k-Assembly.tmLanguage so perhaps you can cross-check your extension with it

**Comment by prb28** [comment]
Thanks!
Do you have a link to a **documentation** containing all these instructions and their variants ?
I'm going to cross-check the Xcc instructions.
I've the same language tmLanguage description in the extension so shs is accepted as an instruction in syntax highlighing, but I didn't find it in the "Motorola MC68000 Programmers Reference Manual".

**Comment by prb28** [comment]
As I understand: SHS and SHI are aliases of SCC. (https://debrouxl.github.io/gcc4ti/a68k.html)

**Comment by prb28** [comment]
Found this doc: with the Xhs mnemonics: http://www.tigernt.com/onlineDoc/68000.pdf
