### ISSUE TITLE
Better documentation with examples for ASM instructions

### ISSUE THREAD

**Issue by prb28** [prb28/vscode-amiga-assembly#75]
from #74

**Comment by tehKaiN** [comment]
How about adding huge checklist for each instruction along with one sample description of ASM instruction written by you? Each one of us could describe one instruction or two here in the comments, simplifying job for you. ;)

If you don't have an idea on how such description should look like, perhaps we should brainstorm it here?

Also, [this info](https://wiki.neogeodev.org/index.php?title=68k_instructions_timings) may be useful, so perhaps there's a way to add it too?

**Comment by prb28** [comment]
I agree with, I'll start a project with all markdown files one per command. And I will merge the pull requests.

And lets try to figure how a command markdown should look like.
Here is a example (source: http://mrjester.hapisan.com/04_MC68/Sect06Part03/Index.html):

---

# BNE – Branch on Not Equal
If the Z flag of the CCR is clear, the destination operand will be added to the PC, and the 68k will continue reading at the new offset held in PC.  If the Z flag is set, the instruction is ignored.
## Example
This is the opposite of BEQ:
```asm
cmpi.w    #$0020,d0
bne.s     FlagZIsClear
move.w    #$0000,d0 
FlagZIsClear:
```
## Details
The CMP instruction runs a comparison of 0020 and the word inside d0:
- If they do not match, then the Z flag will be cleared.  And the 68k will branch to `FlagZIsClear`
- If they match, then the Z flag will be set.  The 68k will continue to `move.w #$0000,d0`
The BNE instruction will only branch if the Z flag is cleared.  If it is set, it will ignore the branch and continue.

**Comment by prb28** [comment]
A good source: http://www.tigernt.com/onlineDoc/68000.pdf

**Comment by prb28** [comment]
With the last documentation the command looks like (looks better):
# Bcc - Branch on condition cc
## Operation
`If cc = 1 THEN [PC] ← [PC] + d`
## Syntax
`Bcc <label>`
## Sample syntax
```
BEQ Loop_4
BVC *+8
```
## Attributes
`BEQ` takes an 8-bit or a 16-bit offset (i.e., displacement).
## Description
If the specified logical condition is met, program execution continues at location [PC] + displacement, d. The displacement is a twos complement value. The value in the PC corresponds to the current location plus two. The range of the branch is -126 to +128 bytes with an 8-bit offset, and -32K to +32K bytes with a 16- bit offset. A short branch to the next instruction is impossible, since the branch code 0 indicates a long branch with a 16-bit offset. The assembly language form `BCC` *+8 means branch to the point eight bytes from the current PC if the carry bit is clear.

|Mnemonic|Description|Logic|
|--|--|--|
|BCC| branch on carry clear|C|
|BCS|branch on carry set|C|
|BEQ| branch on equal|Z|
|BGE|branch on greater than or equal|N.V + N.V|
|BGT| branch on greater than|N.V.Z + N.V.Z|
|BHI| branch on higher than|C.Z|
|BLE| branch on less than or equal|Z + N.V + N.V|
|BLS| branch on lower than or same|C+Z|
|BLT| branch on less than|N.V + N.V|
|BMI| branch on minus (i.e., negative)|N|
|BNE| branch on not equal|Z|
|BPL| branch on plus (i.e., positive)|N|
|BVC| branch on overflow clear|V|
|BVS| branch on overflow set|V|

Note that there are two types of conditional branch instruction:
- those that branch on an unsigned condition and those that branch on a signed condition. For example, $FF is greater than $10 when the numbers are regarded as unsigned (i.e., 255 is greater than 16). However, if the numbers are signed, $FF is less than $10 (i.e., -1 is less than 16).

The signed comparisons are:

|Mnemonic|Alias|Description|
|--|--|--|
|BGE||branch on greater than or equal
|BGT||branch on greater than|
|BLE||branch on less than or equal|
|BLT||branch on less than|

The unsigned comparisons are:

|Mnemonic|Alias|Description|
|--|--|--|
|BHS|BCC|branch on higher than or same|
|BHI| |branch on higher than|
|BLS| |branch on lower than or same|
|BLO|BCS| branch on less than|

The official mnemonics `BCC` (branch on carry clear) and `BCS` (branch on carry set) can be renamed as `BHS` (branch on higher than or same) and `BLO` (branch on less than), respectively. Many 68000 assemblers support these alternative mnemonics.

## Condition codes

|X|N|Z|V|C|
|--|--|--|--|--|
|-|-|-|-|-|

**Comment by prb28** [comment]
I've an [agreement](https://community.nxp.com/thread/510780) from NXP, just have to mention the source in the documentation.

**Comment by prb28** [comment]
started repository: https://github.com/prb28/m68k-instructions-documentation

**Comment by prb28** [comment]
![image](https://user-images.githubusercontent.com/10462286/87731299-72b4e380-c7ca-11ea-9175-ffc6ff96c4d2.png)

**Comment by howprice** [comment]
Hi. I'm developing a disassembler that would benefit from this documentation. Can I please ask how you went about requesting permission to include information from the M68000PRM?

**Comment by prb28** [comment]
It was easy, getting in touch with nxp in their forum.

**Comment by howprice** [comment]
Thanks very much. I'll have a look.
