### ISSUE TITLE
Source file names always upper case on windows when debugging

### ISSUE THREAD

**Issue by geijer** [prb28/vscode-amiga-assembly#80]
My source file is called `Info.s` but when debugging on Windows VSCode opens a file called `INFO.S` with the same path even if `Info.s` is already open.

Because Windows file system isn't case senstitive it results in the same file opened twice with different case in the names.

Have verified that the Amiga binary included the correct path and name.

Edit: linux & macos works as expected.

**Comment by prb28** [comment]
This issue is due to vscode https://github.com/microsoft/vscode/issues/12448.
I will try to add a workaround.
