### ISSUE TITLE
A0 & D0 contains wrong values on debug entry

### ISSUE THREAD

**Issue by geijer** [prb28/vscode-amiga-assembly#81]
From the Amiga Guru Book 20.2.1.1:
"• D0 contains the length of the argument string;
• A0 contains a pointer to the argument string.
This command line is always terminated by a line feed (ASCII $0A == LF), so it is at least one character long."
But the debugger starts with D0=0 and A0=some invalid memory adress. D0 can only be 0 if started from Workbench with a workbench message, it is not valid from CLI.

If no arguments is passed to the command it should be:
D0=1
A0 points to the string: $a

**Comment by prb28** [comment]
This is due to the way the debugger is integrated in FS-UAE.
It's done before the CLI initialization (the exe is injected in the emulator).
I will look if sending parameters is possible with my understanding of FS-UAE.

**Comment by geijer** [comment]
No problem, it is easy to do a workaround now when I know the symptom.

**Comment by prb28** [comment]
No need to report to emoon, the updates for the last year were done by me ;-).

**Comment by prb28** [comment]
@geijer 
The call to the amiga program is done for kickstart >= 2 by calling RunCommand in the dos library:
```
  rc = RunCommand(seglist, stacksize, argptr, argsize)
  D0		D1	   D2	    D3	    D4
```
And for Kickstart under 2.0 - it's CreateProc
```
  process = CreateProc( name, pri, seglist, stackSize )
  D0                    D1    D2   D3       D4
``` 
I think for the first case that can be fixed adding an argument.
The second... maybe not..
Do you have an idea on how to fix it ? 
or a better way to run the program on old kickstarts ?

**Comment by geijer** [comment]
From Autodocs for RunCommand()
"NOTE: the argument string MUST be terminated with a newline to work properly with ReadArgs() and other argument parsers."

Please let d3 point to dc.b "\n",0 and d4 = 1 when no arguments is passed and it will work on kick >= 2 :)

I'll look into how to handle CreateProc()...

**Comment by prb28** [comment]
Already fixed that in https://github.com/prb28/fs-uae/commit/bd25a3fcfa2f77e9636832923bab144361215f73
From autodocs : 
> It's usually appropriate to set the command name (via
	SetProgramName()) before calling RunCommand().  RunCommand() sets
	the value returned by GetArgStr() while the command is running.

Do you think calling SetProgramName() is important ?

**Comment by geijer** [comment]
Do you think calling SetProgramName() is important ?

No, not if there is a name set. But I guess that it can be a problem if there isn't any name at all.

**Comment by prb28** [comment]
New integration of fs-uae should resolve this bug.
