### ISSUE TITLE
debug device driver

### ISSUE THREAD

**Issue by terriblefire** [prb28/vscode-amiga-assembly#82]
Is there any way to debug a device driver that I have building in vscode?

**Comment by prb28** [comment]
I don’t know how a driver is loaded in Amiga. Have you tried to start a program using the driver in the debug? With luck it will catch the breakpoint in the driver...

Maybe the new debug console of winuae is more adapted.

**Comment by terriblefire** [comment]
I will investigate this a bit. I think the best way to get this to work might be to have a self installing driver which i think is possible. 

Will report back and update the wiki if necessary

**Comment by prb28** [comment]
Thanks that would be great.

**Comment by terriblefire** [comment]
OK i have discovered two impediments to this. 

Firstly the UAE Debugger crashes with an illegal instruction when the process being debugged exits. 

Secondly I would need to be able to keep the debugger running after the program exits. 

Both of these seem to be FS-UAE issues. Is there any possibility to integrate with WinUAE?

**Comment by prb28** [comment]
Toni Wilen may add it to winuae later this year, but it's not shure.

**Comment by terriblefire** [comment]
Ah I can persuade Toni :) 

What is needed and I’ll ask

**Comment by prb28** [comment]
He agreed to add in a major release, what I fully understand.

**Comment by prb28** [comment]
Will be fixed with https://github.com/prb28/vscode-amiga-assembly/issues/114
