### ISSUE TITLE
-devpac option breaks source debugging

### ISSUE THREAD

**Issue by terriblefire** [prb28/vscode-amiga-assembly#84]
if I build code with the -devpac option then it breaks source level debugging. It gives me a segment debug instead. 

You can try this with the standard example gencop.s

**Comment by prb28** [comment]
Looks like a feature of vasm ([documentation](http://sun.hasenbraten.de/vasm/release/vasm.pdf)):
> -devpac
> All options are initially set to be Devpac compatible. Which means that all optimizations are disabled, no debugging symbols will be written and vasm will warn about any optimization being done. When symbol output is enabled by opt d+, then the TOS symbol table defaults to standard DRI format (limited to 8 characters). Shift-right operations are performed using an unsigned 32-bit value. Other options are the same as vasm’s defaults. The symbol __G2 is defined, which contains information about the selected cpu type. The symbol __LK reflects the type of output file generated. Which is 0 for TOS executables, 4 for Amiga executables and 3 for Amiga object files. All other formats are represented by 99, as they are unknown to Devpac. It will also automatically enable -guess-ext.

**Comment by terriblefire** [comment]
opt d+ should fix it
