### ISSUE TITLE
Debugger does not follow lables

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#92]
In the current release the debugger does not follow jumps to labels. This makes the work much more difficult. :( 
The symbols were created (switch -linedebug).

**Comment by Real-MJoe** [comment]
Okay, you're right! After a reinstall of VSCode extension it works as it should.
SORRY my mistake. :/ 

OT:
But creating a file with big letters in the debugger is annoying. It has already been fixed. But when comes the veriosn 0.18 :D

**Comment by prb28** [comment]
Great!

Someone told me that some settings in the workspace can drive the debugger mad, but I haven’t seen it yet.

The release is coming soon... I’ve to build the native executables and test a bit on the 3 platforms...
