### ISSUE TITLE
[feature] Generate Boot Block Code

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#95]
It would be nice if it were possible to program a boot block and transfer it to an ADF. 
Info:
The vasm can generete the code with switch "-Fbin". But the checksum is also needed of the binary.

**Comment by prb28** [comment]
@Real-MJoe how do you this option should be?
- Create a new ADF file with the boot block or add the it to an existing file?
- Code the binary data at the beginning ('DOS...') or generate it ?
Other thoughts?

Documentation: http://lclevy.free.fr/adflib/adf_info.html#p41

**Comment by endo64** [comment]
What about both options? Generate the binary file or generate the ADF file with the bootblock?

**Comment by prb28** [comment]
Both will be generated. The vasm build will produce a binary in the build dir, then the adf file will be produced using it.

**Comment by Real-MJoe** [comment]
It would be nice if you could compile a *.s file using a command and then write it to an empty ADF. Of course the checksum for the BootBlock has to be calculated. But the calculation is quite simple.

In ASMONE its very simple to do it all:
>Editor:

BOOT:
  dc.l "DOS"<<8
  dc.l 0
  dc.l 0

START:
  moveq #0,d0
  rts.
    
; To write this code to disk with ASM-One you'd use:
> WS

RAM PTR>Boot
DISK PTR>0
LENGTH>2

**Comment by prb28** [comment]
Can you please try the pre-release ?
The extension: https://github.com/prb28/vscode-amiga-assembly/releases/tag/0.19-test-1
(The new binaries are not needed for this issue)
The example workspace : https://github.com/prb28/vscode-amiga-bblock-example
The wiki page: https://github.com/prb28/vscode-amiga-assembly/wiki/ADFTools 

Thanks

**Comment by Real-MJoe** [comment]
First, thx for the test release. But is not work for me. 
The disk.adf and *.bb (binary boot block code) is still generated. But it is not copy to adf. 

Ontop is the generated adf file. Botton the bootblock code.
![grafik](https://user-images.githubusercontent.com/40276633/70869472-a5c09b80-1f8b-11ea-94ba-e60338633cc3.png)

Maybe a config fault at me?

**Comment by prb28** [comment]
Thanks for the test.
Yes, looks like the boot block is truncated in the adf file.
I must try with a bigger one (of nearly 1Kb).

**Comment by prb28** [comment]
I've filled my boot block with data values at end and have everything in the adf...
Maybe there is something in you boot block that reveal a bug in adftools.
The command to install the bb file is:
`bin/adfinst --install=build/myboot.bb build/disk.adf`
 
@Real-MJoe Can you send me your source or binary *.bb file ?
If not the first 200 bytes of the bb file may be enough to reproduce the bug.

**Comment by prb28** [comment]
@Real-MJoe , I found it, it's a bug on windows platform.
I'll fix it soon.

**Comment by Real-MJoe** [comment]
That sounds really good. Thank you for your efforts!

**Comment by prb28** [comment]
Could you please try this adfinst binary ?
https://github.com/prb28/vscode-amiga-assembly-binaries/blob/windows_x64/adfinst.exe
Put it in the bin directory. Hope it works ;-).

**Comment by Real-MJoe** [comment]
This is working the way it's supposed to. As always, great work, thank you.

**Comment by Real-MJoe** [comment]
Oh well, this error is shown in the *..code-workspace file but it still works.

![grafik](https://user-images.githubusercontent.com/40276633/70937292-57bb9e80-2044-11ea-99aa-4d51868390ed.png)

**Comment by prb28** [comment]
Great! Thanks.
Haven’t seen this message, thanks for reporting.
