### ISSUE TITLE
List used registers sometimes incorrect

### ISSUE THREAD

**Issue by jonathanbennett73** [prb28/vscode-amiga-assembly#99]
Hi when I do list used registers on the below is says that only d1/a0-a1 is used. :

`
movem.l	(a0)+,d1-d7/a2

movem.l	d1-d7/a2,(a1)
`

0.18 version of extension.

**Comment by prb28** [comment]
Thanks for the issue, as you have noticed, the ranges of registers were not accepted.
Here is the fix:
[amiga-assembly-0.18.2.vsix.zip](https://github.com/prb28/vscode-amiga-assembly/files/3769771/amiga-assembly-0.18.2.vsix.zip)

**Comment by jonathanbennett73** [comment]
Thanks. I really like this feature :) :)
